#+latex_class: russian

Использованная литература и не только:
Э. Б. Винберг. Курс алгебры.
А. Л. Городенцев алгебра

про бинарные отношения
https://www.csd.uwo.ca/~mmorenom/cs2214_moreno/notes/9-handout.pdf
https://economics.hse.ru/data/2019/09/16/1541173496/%D0%A1%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%80%202%20-%20%D0%B1%D0%B8%D0%BD%D0%B0%D1%80%D0%BD%D1%8B%D0%B5%20%D0%BE%D1%82%D0%BD%D0%BE%D1%88%D0%B5%D0%BD%D0%B8%D1%8F%20(%D0%BD%D0%B0%20%D1%81%D0%B0%D0%B9%D1%82).pdf
лекция по алгебры НМУ: https://www.youtube.com/watch?v=T45ZtSk3d38

Алгебра изучает алгебраические структуры.  
#+begin_definition
Алгебраической структурой мы будем называть множество \(\mathbb{M}\) вместе с набором операций.
#+end_definition

\(\mathbb{M}\) - множество, \(\mathbb{M}\times \mathbb{M}=\{(a,b)|a,b\in \mathbb{M}\}\)
* Отображение /Функция *
#+begin_definition 
Отображение \(f: \mathbb{X}\to \mathbb{Y}\). Существует правило в множествах \(\mathbb{Y}\) и \(\mathbb{X}\) сопостравляющее каждой \(x\in \mathbb{X}\)  однозначно определяемую точкку \(y=f(x)\in \mathbb{Y}\), называется образом точки \(x\) при отображении \(f\).
#+end_definition

#+begin_definition
\(\operatorname{Hom}(\mathbb{X}, \mathbb{Y})\) множество всех отображений из множества \(\mathbb{X}\) в \(\mathbb{Y}\)
#+end_definition

Множество всех точек \(x\in \mathbb{X}\) образ которых равен данной точке \(y\in \mathbb{Y}\) называется полным прообразом точки \(y\) (или слоем отображения \(f\) над \(y\)):
\(f^{-1}(y):=\{x\in \mathbb{X}|f(x)=y\}\)

Полные прообразы различных точек не пересекаются, могут быть пустыми, так и состоять из каких-то точек. Множество \(y\in \mathbb{Y}\) с непустым прообразом, называется образом отображения \(\mathbb{X}\xrightarrow{f}\mathbb{Y}\):
\(\operatorname{im}f:= \{y\in \mathbb{Y}|f^{-1}(y)\neq \varnothing\}=\{y\in \mathbb{Y}|\exists x\in \mathbb{X}:f(x)=y\}\)

равенство отображений
\(f=g \iff \forall x\in \mathbb{X}(f(x)=g(x))\)
#+begin_definition 
\(\operatorname{Hom}(\mathbb{X}, \mathbb{Y})\) множество всех отображений из множества \(\mathbb{X}\) в \(\mathbb{Y}\)
#+end_definition
#+begin_prop 
Если множества конечны, то \(|\operatorname{Hom}(\mathbb{X}, \mathbb{Y})|=|\mathbb{Y}|^{^{|\mathbb{X}|}}\)
#+end_prop
\\ написать док-во, потом 
** Сюръекция, инъекция, биекция
#+begin_definition 
\( \mathbb{X} \twoheadrightarrow \mathbb{Y}\) — наложение(сюрьекция) для \(f: \mathbb{X}\to \mathbb{Y}\) когда  \(\operatorname{im}f=\mathbb{Y}\) прообраз для каждой точки \(y\in \mathbb{Y}\) не пуст.
#+end_definition
#+begin_definition 
\(\mathbb{X}\hookrightarrow \mathbb{Y}\) - вложение (инъекция или мономорфизм) \(f(x_1)\neq f(x_2)\) когда прообраз каждой точки \(y\in \mathbb{Y}\) не содержит более одного элемента.
#+end_definition
#+begin_definition 
\(\mathbb{X}\xrightarrow{\sim} \mathbb{Y}\)Биекция — соблюдаются два предыдущих свойства.
#+end_definition
#+latex: \newpage
** Эндоморфизмы
#+begin_definition 
Эндоморфизм(отображение само в себя) \(\mathbb{X}\to \mathbb{X}\)
множество эндомормизмов \(\operatorname{End}(\mathbb{X})=\operatorname{Hom}(\mathbb{X}, \mathbb{X})\)
#+end_definition

#+begin_definition 
Взаимно однозначные эндорфизмы называются автоморфизмами \(\mathbb{X}\).
\(\mathbb{X}\xrightarrow{\sim} \mathbb{X}\)
\(\operatorname{Aut}(\mathbb{X})\) Множество всех автоморфизмов
Автоморфизмы это как перестановка элементов множества \(\mathbb{X}\)
#+end_definition

У всякого множества есть тождественный автоморфизм \(\operatorname{Id}_{\mathbb{X}}:\mathbb{X}\to \mathbb{X}\), который переводит каждый элемент в самого себя \(\forall x\in \mathbb{X}\ \operatorname{Id}_{\mathbb{X}}(x)=x\)

** Слои отображений / Прообразы
#+begin_definition 
Задание отображения \(f: \mathbb{X}\to \mathbb{Y}\) равносильно разбиению \(\mathbb{X}\) в дизъюнктивное объединение непустых подмножеств \(f^{-1}(y)\) занумерованных точками \(y\in \text{im}(f)\)
\(\mathbb{X}=\bigsqcup_{y\in \text{im}(f)}f^{-1}(y)\)
#+end_definition

* Бинарная операция 
#+begin_definition 
Бинарной операцией на множестве \(\mathbb{M}\) называется отображение:
\[ *: \mathbb{M} \times \mathbb{M} \to \mathbb{M} \]
#+end_definition
Результат применения операции к паре \((a, b)\) обозначается \(a * b\).
\(\forall x, y\in \mathbb{S}\ \exists !\ z\in \mathbb{S}(z=x*y)\)

#+begin_remark 
   \((\mathbb{S}, *)\) будем называть алгеброй.

если операция записана с помощью знака +, то такая форма записи называется аддитивной.
с помощью знака умножения мультипликативной.
#+end_remark

#+begin_proof
Примеры бинарной операции:

   1) \((\mathbb{N}, +)\)
      \((\mathbb{Z}, +)\)
   3) \(\mathbb{V}\) = { Вектора на плоскости }
   4) множество, \((\text{Map}(m,m), \circ)\) (Map - множество отображений)
      \(\{\mathbb{M} \xrightarrow{f} \mathbb{Y}\}\)
#+end_proof

      \(\mathbb{M}\xrightarrow{g} \mathbb{M}\xrightarrow{f} M\) или \(f(g(x))\)
#+begin_definition 
   Опр. множество на котором задана бинарная операция называется группоидом (результат должен принадлежать тому же множеству).
#+end_definition

* Гомоморфность  / homomorphism
#+begin_definition 
Есть \((\mathbb{M}, \circ)\)  и \((\mathbb{N}, *)\) они гомоморфны если есть  \(f: \mathbb{M}\to \mathbb{N}\)

\(\forall a, b \in \mathbb{M}(f(a \circ b) =f(a)*f(b))\)
#+end_definition

#+begin_definition 
Изоморфны, если гомоморфны и биективны
обозначается:
\( (\mathbb{M}, \circ)\simeq (\mathbb{N}, *)\)
Само отображение f называется изоморфизмом этих структур.
#+end_definition

#+begin_proof 
Пример:
\(a\to 2^a\)

\((\mathbb{Q}, +)\simeq (\mathbb{R}^+, *)\)
#+end_proof

свойства изоморфных алгебр, если две алгебры изоморфны:
1) образ нейтрального элемента — нейтральный элемент
2) образ симметричного элемента — элемент симметричный образу
3) образ полугруппы — полугруппа
4) образ группы — группа.
5) сохранение коммутативности в алгебрах

рассмотрим алгебры с двумя бинарными операциями, такие алгебры называются изоморфными, если существует биекция одного множества на другое, сохраняющие обе операции.

Свойства:
Если изоморфны алгебры с двумя операциями, то:
1) образ единицы — единица.
2) образ нуля — ноль.
3) Образ противоположного элемента — элемент противоположный образу.
4) Образ обратного элемента — обратный образу.

Если одна из изоморфных алгебр кольцо то и вторая тоже. 
Если одна из изоморфных алгебр поле то и вторая тоже. 

Рассмотрим пример, поле комплексных чисел:
\(C=\{\alpha | \alpha =(a,b), a, b \in \mathbb{R}\}\)
сложение \(\alpha=(a, b), \beta =(c, d) \implies \alpha +\beta=(a+c,\ b+d)\)
умножение \(\alpha * \beta =(ac-bd, ad+bc)\)

\((C, +, *) \) - поле

* Простейшие свойства 
1) $\forall a, b, c \in \mathbb{R}(a + (b + c) = (a + b) + c)$ (ассоциативность)
2) $\forall a \in \mathbb{R} \implies a + 0 = 0 + a = a$ 
3) $\forall a \in \mathbb{R}, \exists! (-a) \in \mathbb{R}\  (a + (-a) = 0) \land ((-a) + a = 0)$
4) $\forall a, b \in \mathbb{R}, \, (a + b = b + a)$ (коммутативность)
5) $\forall a, b, c \in R, \, a(bc) = (ab)c$ (ассоциативность)
6) $\forall a \in R, \, a \cdot 1 = 1 \cdot a = a$
7) $\forall a \in R, \, a \neq 0 \implies \exists! a^{-1} \in R \text{ such that } aa^{-1} = 1$
8) $\forall a, b \in R, \, ab = ba$
9) $\forall a, b\in \mathbb{R}(a(b+c)=ab+ac)$
10) \(\forall a,b \in \mathbb{G}\exists ! c\in G(c=a*b)\)
при условии соблюдении 10 аксиомы:

Аддитивная полугруппа это множество \(\mathbb{G}\) с бинарными операциями удволетворяющими аксиоме 1).
    
Аддитивная группа это множество \(\mathbb{G}\) с бинарными операциями удволетворяющими аксиомам с 1) по 3).
    
Абелева группа — группа + 4)
    
Это множество \(\mathbb{R}\) с двумя бинарными операциями 1), 4), 9)
    
Кольцо 1-3, 5).
    
Поле — 1)- 9)
    
\(\theta \subset \mathbb{S}\)  называется нейтральным если \(\forall x\in \mathbb{S}(x*\theta=\theta*x=x)\)

в аддитивной записи, нейтральный элемент — нулевой. в мультипликотивной — единичный(E).

Пусть \(\mathbb{S}\) группоид содержащий нейтральный элемент тогда элемент \(a'\) называется симметричным элементу а, если \(a*a'=a'*a=\theta\)

при аддитивной форме записи симмитричный элемент называется противоположным, при мультипликативной — обратной.
* Основная теорема арифметики [пример, не закончено, не обязательно читать] 
// будет дополнятся [[https://www.youtube.com/watch?v=T45ZtSk3d38][взято отсюда]]

Примеры:

1) \(\mathbb{Z}\) — коммутативное, ассоциативное кольцо с единицей. 

\(\mathbb{Z}^\times =\{a\in \mathbb{Z}| \exists a^{-1}^{}: aa^{-1}=1\}=\{\pm 1\} \)

\((\mathbb{Z}^\times, \cdot)\) — Аббелева группа.

Опр. \(p\in \mathbb{Z}\)    — простое, если необратимо \(p=m*n\), то \(m\in \mathbb{Z}^\times\) или \(n\in \mathbb{Z}^\times\)

** Основная теорема арифметики
Любое ненулевое целое не равное \(\pm1\) число единственным образом представляется в виде произведения простых чисел( с точностью до перестановки и умножения на обратимые).

\(m=p_1...p_k=q_1...q_s\)
\(p_i, q_i\) — простые
то \(k=s\) с точностью до перестановки \(p_i=r_iq_i; r=\pm 1\)

Док. существования. Если число простое, то оно уже разложено, если непростые  числа надо разложить, так как числа уменьшаются, то рано или поздно мы придём к простым числам. \(n=n_1*n_2\) 
Определение делисмости. \(a, b\in \mathbb{N}, b \mid a \iff \exists q \in \mathbb{Z} | a = b \cdot q
\)
Док. единственности:
Лемма Евклида:
p - простое, \(p|ab \implies {a}|{p} \text{ or } {b}|{p}\) 
        
Лемма эквивалентна основной теореме арифметике
        
допустим, число имеет два разных разложения
\(m=p_1...p_k=q_1...q_s\)
\(p_1\) — простое
\({p_1}|{q_1...q_s}\), \({p_1}|{q_1}\) или \({p_1}|{q_1...q_s}\)

\(\exists i\ {p_i}|{q_i}\)
\(q_i =\pm p_i\)
Д-во  леммы Евклида
на \(\mathbb{Z}\) определеннно деление с остатком:
утв. \(\forall a, b\in \mathbb{Z}\ \exists ! q, r| a=b*q+r, \ 0\leq r < |b|\)
        
Наибольший общий делитель:
   1) общий делитель (d|b и d|a)
   2) наибольший с таким свойством.

      Алгоритм евклида:
      НОД(a,b) =НОД(a-b, b)

      \(d|a \implies d|a-b \)

* Свойства бинарных отношений заданных на множестве
Пусть задано бинарное отношение \(\Phi\)  на множестве \(\mathbb{ A }\), оно называется
[[https://www.csd.uwo.ca/~mmorenom/cs2214_moreno/notes/9-handout.pdf][примеры взяты отсюдова]]
Более короткая запись \((x, y)\in \Phi\) === \(x\Phi y\)

1. рефлексивным если для \(\forall x, x\in \mathbb{A} \to (x, x)\in \mathbb{A}\)
   
   примеры:
   
   \(\mathbb{A}=\{(x,y)|x\leq y\}\)
   
   \(\mathbb{A}=\{(x,y)|x= y \text{ or } x=-y\}\)
   
   \(\mathbb{A}=\{(x,y)|x= y\}\)
3. симметричным, если \(\forall x, y\in \mathbb{A}((x,y)\in \mathbb{A}\implies (y, x)\in \phi)\)
   
   \[\mathbb{A} = \{ (x, y) \mid |x| = |y| \} \]
    
   \[\mathbb{A} = \{ (x, y) \mid x = y \} \]
    
   \[\mathbb{A} = \{ (x, y) \mid x + y \leq 3 \} \]
1. транзитивным, если \(\forall x, y\in \mathbb{A}((x, y)\in \phi\land (y, z)\in \phi\implies (x, z)\in\phi)\)
   примеры(\(x, y\in \mathbb{Z}\))
   
   \[\mathbb{A} = \{ (x, y) \mid x \leq y \} \]
    
   \[\mathbb{A} = \{ (x, y) \mid x > y \} \]
    
   \[\mathbb{A} = \{ (x, y) \mid |x| = |y| \} \]
    
   \[\mathbb{A} = \{ (x, y) \mid x = y \} \]
3. отношением эквивалентости если соблюдаются предыдущие три свойства.
   Отношение эквивалентности разбивает множество, на котором оно задано на классы эквивалентности — непустые, попарно непересекающиеся подмножества, объединения которого равны а.
4. иррефлексивным (антирефлексивным), если для \(\forall x\in \mathbb{A} ((x, x)\notin \phi)\)
5. антисимметричным, если для
   \(\forall x, y \in \mathbb{A}((x, y)\in\phi\land (y, x)\in \phi \implies x=y)\)
6. отношением порядка, если выполняются 6 и 3.  Порядок называется строгим, если выполняется 5 и нестрогим — 1. Линейным, если выполняется 8.
7. Связным, если \(\forall (x,y) \in \mathbb{A}, x\neq y ((y, x)\in \phi \lor (x, y)\in \phi)\)

* Простейшие свойства групп
1) Если в группоиде \(S\) cуществует нейтральный элемент (\(\theta\)) — он единственный.
   допустим, есть два нейтральных элемента \(\theta\) и \(\lambda\):
   \(\theta =\theta * \lambda \land \lambda = \lambda * \theta \implies \lambda = \theta\)

2) Если в полугруппе \(S\) cуществует для элемента а существует симметричный/противоположный — он единственный.
   Допустим, для a есть два противоположных элемента a'_1 и a'_2, в таком случае:
   \(a*a'_1=e \land a*a'_2=e \implies a*a'_1=a*a'_2 \implies a'_1=a'_2\)
3) Для любых a, b уравнение x * a = b имеет единственное решение, равное b * a'(где a' - обратный элемент a), называющееся в аддитивной группе вычитанием и в мультипликативной делением. 
4) В мультипликативной форме записи понятие натуральной степени элемента можно вести в полугруппе, понятие целой степени — в группе.
   Для нулевой степени нужен нейтральный элемент, а для отрицательной — обратный, для натуральной степени достаточно ассоциативности.

* Подгруппа   
\(H\subset G\)   называется подгруппой, если относительно операции определённой в \(G\) оно само образует группу.

*Это самые минимальные требования для подгруппы, взяты из abstract algebra. Могут не подойти для основного курса.*
подмножество \(\mathbb{H}\subset \mathbb{G}\) является подгруппой, если
1. \(H\neq \varnothing\)
2. \(\forall x, y \in \mathbb{H}, xy^{-1}\in \mathbb{H}\)
  Для группы должно выполнится четыре условия:
   1. Ассоциативность обеспечена использованием элементов из \(\mathbb{H}\) .
   2. Наличие нейтрального элемента допустим, что \(y=x\) => \(xx^{-1}\in \mathbb{H}( xx^{-1} =\theta \implies \theta \in \mathbb{H})\).
   3. Наличие противоположного => исходя из условия 2 и равенства \(y=x\).
   4. Замкнутость => допустим, что \(y=y^{-1}\) в таком случае \(x(y^{-1})^{-1}\in \mathbb{H} \implies xy\in \mathbb{H}\).
    
   Всякая группа имеет две тривиальных подгруппы(все подгруппы помимо них называются собственными):
      1) \(\{\theta\}\)
      2) \(\mathbb{G}\)

Пусть \(\mathbb{G}\) — мультипликативная группа, \(a\) – её фиксированный элемент.  Если любой элемент \(g\in \mathbb{G}\) записывается в виде \(g=a^n\) для некоторого \(n\in \mathbb{Z}\), то \(\mathbb{G}=<a>\) — циклическая группа с образующим а(или циклическая группа порождённая а)

аналогично циклическая группа определяется в аддитивном случае:
\(<a>=\{na|n\in \mathbb{Z}\} \)

* кольцо
Элементы кольца, обладающие свойством \(a\neq 0\) \(b\neq 0 \) \(\)\(ab=0\) делить нуля.
Коммутативное кольцо с еденицией без делителей нуля называется областью целостности.


\(\mathbb{K}=\{C_0, C_1, C_2, C_3\}\)
| +   | C_0 | C_1 | C_2 | C_3 |
|-----+-----+-----+-----+-----|
| C_0 | C_0 | C_1 | C_2 | C_3 |
| C_1 | C_1 | C_2 | C_3 | C_0 |
| C_2 | C_2 | C_3 | C_0 | C_1 |
| C_3 | C_3 | C_0 | C_1 |  C_2 |

| *   | C_0 | C_1 | C_2 | C_3 |
|-----+-----+-----+-----+-----|
| C_0 | C_0 | C_0 | C_0 | C_0 |
| C_1 | C_0 | C_1 | C_2 | C_3 |
| C_2 | C_0 | C_2 | C_0 | C_2 |
| C_3 | C_0 | C_3 | C_2 | C_1 |

Разность кольца А и б называют суммой a и b.

Замечание. Кольцо можно определить иначе. Кольцом называется алгебра с двумя операциями: сложение и умножение, если относительно операции сложения оно образует абелеву группу, относительно умножения полугруппу и обе операции связаны свойством дистрибутивности.

1) так как кольцо является абелевой группой по сложению, то для его элементов выполняются все свойства абелевых групп и полугрупп по умножению.
2) \(\forall a\in \mathbb{K}(a*0=0*a=0)\)
3) в произвольном кольце справедливо правило знаков \(\forall a, b\in \mathbb{K}\)  \((-a)(-b)=ab\) \((-a)b=a(-b)=-ab\) \(-(a)=a\)
4) \(\forall a, b, c\in \mathbb{K} a(b-c)=ab-ac (b-c)a=ba-ca\)
5) справедлив бином ньютона \(\forall a, b\in \mathbb{K}\forall n\in \mathbb{N} (a+b)^n=\sum ^n_{i=o}C_na^{n-i}b^i\)
   \(C_n^i=\frac{n !}{i!(n-i)!}\)
   Удобно использовать треугольник Паскаля для нахождения коэффициентов.
   
* подкольцо
\(K'\subset \mathbb{K}\) называется подкольцом кольца К, если относительно операций в К, оно само образует кольцо
Для того чтобы оно было подкольцом, необходимо и достаточно, нужно, чтобы выполнялись след условия:

1) \(\forall a, b\in {K}' (a+b\in K')\)
2) \(\forall a, b \in ' {K} (a-b\in K')\)
3) \(\forall a, b\in K'(ab\in K')\)
   
\(K' ={x|x=5k, k\in \mathbb{Z}}\)
\(K' \in \mathbb{Z}\)

Пусть \(x_1, x_2\in K'\iff x=5k, x_2=5k, \text{where } k_1, k_2 \in \mathbb{Z}\implies \)
\(x_1+x_2=5k_1+5k_1=5(k_1+k_2)\in K', k_1+k_2\in \mathbb{Z}\)
\(x_1-x_2=5k_1-5k_1=5(k_1-k_2)\in K', k_1+k_2\in \mathbb{Z}\)
\(x_1*x_2=5k_1*5k_1=5(k_1*k_2)\in K', k_1+k_2\in \mathbb{Z}\)

* поле
(P, +, *) коммутативное кольцо с единицей для каждого ненулевого элемента есть обратный называется полем.
\((P, +, *)\) называется полем
относительно + абелева группа, относительно умножения коммутативная группа \(P\setminus \{\varnothing\}\) и есть дистрибутивность

\(\mathbb{Q}. \mathbb{R}\) — поля
Будем называть дробям, \(\frac{a}{b}=ab^{-1}\)

для его элементов справедливы все свойства колец, в поле нет делителей нуля
док-ть самостоятельно.

\(\frac{-a}{-b}=\frac{a}{b}\)
\(\frac{-a}{b}=\frac{a}{-b}=-\frac{a}{b}\)
\(\frac{a}{b}\pm \frac{c}{d}=\frac{ad\pm bc}{bd}\)
\(\frac{a}{b}*\frac{c}{d}=\frac{ac}{bd}\)
\((\frac{a}{b})^{-1}=\frac{b}{a}\)

* подполе
\(P'\subset P\) - называется подполем, если сохраняет свойства поля относительно операций определённых в Р.

\(\mathbb{Q}\subset \mathbb{R}\) — подполе, а R расширение Q

Для того чтобы \(P'\subset P\) было подполем, необходимо и достаточно выполнение след условий:
1) \(\forall a, b\in P' (a+b\in P')\)
2) \(\forall a, b\in P'(ab\in P')\)
3)\(\forall a, b\in P'(b\neq 0)(\frac{a}{b}\in P')\) 

* комплексное поле
#+begin_theorem 
Поле C содержит подполе изоморфное полю действительных чисел
#+end_theorem
#+begin_proof 
\(R_1=\{\alpha | \alpha =(a, 0), a\in \mathbb{R}\}\)

докажем, что \(R_1\) - поле. Так как, \(R_1\subset C\), то можно воспользоваться теоремой о подполе. Пусть \(\alpha, \beta \in R \iff \alpha =(a, 0), \beta=(b, 0), a, b\in \mathbb{R} \implies \alpha +\beta =(a+b, 0+0)=(a+b, 0)\in \mathbb{R}_1, a+b\in \mathbb{R}\)
\(\alpha -\beta (a-b, 0-0) =(a-b, 0)\in {R_1}, a-b\in \mathbb{R}\)
\(\alpha* \beta=(a,b)( b,0) =(ab-0*0, a*0+0*b)=(ab,0)\in {R_1}, ab\in \mathbb{R}\)
\(\frac{\alpha}{\beta}=\alpha *\beta^{-1 }=(a,0)(\frac{1}{b}, 0)=(\frac{a}{b}-0*0, 0*0+\frac{0}{b}=(\frac{a}{b}, 0)\in R_1, \frac{a}{b}\in \mathbb{R})\)
#+end_proof

#+begin_proof 
\( R_1\simeq \mathbb{R}\)
\(\phi : R_1\to \mathbb{R} \forall \alpha \in R_1 (\alpha =(0,0))\phi (\alpha)=a, \in \mathbb{R}\)
пусть \(k\in \mathbb{R}\implies \gamma =(k,0)\in R_1\to \thi(\gamma)=k\)
\phi - сюрьекция
\(\alpha_1\neq \alpha_2 \iff (a, 0)\neq (a_2, 0)\iff a_1\neq a_2\iff \phi(\alpha_1)\neq \phi(\alpha_2)\iff \) \phi - инъекция, \phi - биекция
#+end_proof

Проверим сохранение операций
#+begin_proof 
Пусть \(\alpha , \alpha \in R_1 \iff \alpha =(a, 0), \alpha_2 = (a_2, 0), a_1, a_2\in R\)
\(\phi(\alpha _1)=a, \phi (\alpha)=a_2\)
\(\alpha_1+\alpha_2 =(a_1+a_2, 0)\) где \(a_1+a_2\in \mathbb{R} \implies \phi (\alpha_1+ \alpha_2)=a_1+a_2=\phi(\alpha_1)+\phi(\alpha_1) \alpha_1\alpha_2 =(a_1a_2,0)\)гдt \(a_1, a_2\in \mathbb{R}\to \phi(\alpha_1\alpha_2)=a_1a_2=\phi (\alpha_1)\phi(\alpha_2)\) 
#+end_proof
на основе доказаной теоремы можно считать поле Р подполем С
Любое подполе поля С называется числовым полем, элементы поля С называются числами.
Любое его подкольцо - числовое кольцо.

На основание доказанной теоремы будем отождествлять упорядоченную пару \((a,0)=a\) пару \((0,1)=i\) и назовём мнимой единицей.

\(i^2=(0,1)(0,1)=(0*0-1*1, 0*1+1*0)=(-1,0)=-1\)

\(\forall a\in \mathbb{C}, \alpha =(a, b)=(a,0)+(0,b)=(a,0)+(b,0)*(0,1)=a+bi\)
получили алгебраическую запись комплексного числа.

Действия над комплексными числами записанные в алгебраической форме 

\(\mathbb{C}=\{\alpha|\alpha =(a,b),a, b\in \mathbb{R}\\{\alpha|\alpha =a+bi, a, b\in \mathbb{R}\}\)
а - действительная часть
bi - мнимая часть
1) равенство \(\alpha =a+bi, \beta =c+di\) \(\alpha =\beta \iff \begin {cases}a=c\\ b=d\end{cases}\)
2) сложение \(\alpha +\beta =(a+bi)+(c+di)=(a+c)+(b+d)i\)
3) умножение \(\alpah *\beta =(a+bi)(c+di)=ac+bdi^2+bci+adi=(ac-bd)+i(bc+ad)\)

   #+begin_definition 
\(\alpha =a+bi, \--- \alpha =a-bi\) комплексно сопряженные

   #+end_definition
\(\alpha +\- \alpha =2a\in \mathbb{R}, \alpha \- \alpha =a^2-b^2c^2=c^2+b^2\in \mathbb{R}\)
\(\- \alpha \pm \- \beta =\-{\alpha +\beta}\)
\(\- \alpha * \- \beta =\-{\alpha\beta}\)
\((\- \alpha)^k=\-{\alpha^k}\)
деление:
\(\frac{\alpha}{\beta}=\frac{a+bi}{c+di}=\frac{(a+bi)(c-di)}{(c+di)(c-di)}=\frac{ac-bdi^2+bci-adi}{c^2-d^2i^2}=\frac{(ac+bd)+(bc-ad)i}{c^2+d^2}= \frac{ac+bd}{c^2+d^2}+i \frac{bc-ad}{c^2+d^2}\)
возведение в степень выполняется с помощью бинома ньютона с учётом того что \(i^2=-1\)

рассмотрим возведение в степень

\((3+2i)^4=3^4+4*3^3*2i+6*3^2(2i)^2+4*3(2i)^3+(2i)^4=81+216i+216i^2+96i^3+16i^4=81+216i-216-96i+16=-119+120i\)
Операция извлечения в алгебраической форме не очень удобна, рассмотрим на примере:
Обозначим:
\(\sqrt{-16}=x+yi\)
\(-16=(x+yi)^2\iff -16 =x^2+2x+2\)
\(-16=(x^2-y^2)+2xyi+y^2i^2\)
\(\begin{cases}x^2-y^2=-16 \\ 2xy=0\end{cases}\)
\(x=0, y^2=16, y=\pm 4\)
\(y=0, x^2=-16 x\notin \mathbb{R}\)
\((0;4)(0;-4)\)

** геометрическое представление комплексных чисел
очевидно, что всякому комплексному числу можно поставить в соответствие единственную точку декартовой плоскости с координатами (a, b), если b равно нулю, то а - действительное число, соответствуюшая точка расположена на оси ох, поэтому ось х называют действительной осью. Если а равно нулю, то альфа мнимое число, то соответсвующее ему число расположено на оси y, поэтому ось игрик называют мнимой осью. 

Известно, что положение любой точки плоскости однозначно определяется либо парой декартовых координат, либо парой полярных координат( длиной вектора и углом наклона радиус вектора).
Длина радиус-вектора соединяющая точку альфа с началом, называется модулем \(r=|\alpha|=\sqrt{a^2+b^2}\)
угол же называется аргументом комплексного числа \(\phi = \operatorname{arg}\alpha\) \(\begin{cases} \cos \phi = \frac{\alpha}{r} \\ \sin \phi =\frac{\beta}{r}\end{cases}\)
\(\alpha \in \mathbb{C}, \alpha =a+bi=\sqrt{a^2+b^2}(\frac{a}{\sqrt{a^2+b^2}}+i \frac{b}{\sqrt{a^2+b^2}})=r(\cos\phi i\sin \phi)\)
получили тригонометрическую форму записи комплексного числа


