#+latex_class: russian
* некоторые определения
k — основное поле
элементы поле k - скаляры.

#+begin_definition 
Линейное(векторное) пространство над полем k. Множество с двумя операциями "\(+\)" и "\(*\)".

\[+ : V\times V\to V (u, v)\to u+ v \] .
\[ *:V\times V\to V (u, v)\to u* v\]
#+end_definition
аксиомы, которые должны выполняться:
1. \( \forall u, v \in V \, (u + v = v + u) \)
2. \( \forall u, v, w \in V \, ((u + v) + w = u + (v + w)) \)
3. \( \exists 0 \in V \, \forall v \in V \, (v + 0 = v) \)
4. \( \forall v \in V \, \exists (-v) \in V \, (v + (-v) = 0) \)
5. \( \forall \lambda \in k \, \forall u, v \in V \, (\lambda \cdot (u + v) = \lambda \cdot u + \lambda \cdot v) \)
6. \( \forall \lambda, \mu \in k \, \forall v \in V \, ((\lambda + \mu) \cdot v = \lambda \cdot v + \mu \cdot v) \)
7. \( \forall \lambda, \mu \in k \, \forall v \in V \, (\lambda \cdot (\mu \cdot v) = (\lambda \mu) \cdot v) \)
8. \( \forall v \in V \, (1 \cdot v = v) \)

#+begin_prop 
\\
- \( \forall v, \lambda \in V \, (\mathbf{0}* v = \mathbf{0}*\lamba= \mathbf{0}) \)  

- \( \forall v \in V \, ((-1) \cdot v = -v) \)

- \( \forall \lambda \in k \, \forall v \in V \, ((\lambda \cdot v = \mathbf{0}) \implies (\lambda = 0 \lor v = \mathbf{0})) \)
#+end_prop
\\ доказывать не буду

#+begin_exam 
1. Множество {0}, состоящее из одного элемента 0, является линейным пространством над любым полем.
2. Множества векторов на прямой, на плоскости, в пространстве, являются линейными пространствами над полем \(\mathbb{R}\).
3. Поле k является векторным пространством над самим собой.
#+end_exam
   
#+begin_definition 
Множество \(W\subset V\) линейного пространства \(V\)  называется подпространством, если для любых векторов \(u, v \in W\)  и скаляра \(\lambda \in k\) если оно само является пространством, соответственно выполняются эти аксиомы:
1) \(u+v\in W\)
2) \(\lambda u\in W\)
#+end_definition
#+begin_exam 
Вот некоторые примеры подпространств.
1. {0) является подпространством в любом пространстве V.
2. Множество векторов, коллинеарных заданному вектору, является подиространством в пространстве всех векторов на плоскости или в пространстве.
3. Пространство \(C(\mathbb{R})\) непрерывных функций является подпространством в пространстве \(\mathbb{R}^{\mathbb{R}}\) всех функций на \(\mathbb{R}\).
#+end_exam

* линейная зависимость, базис, размерность
#+begin_definition 
Пусть \(V\) — линейное пространство над полем k.
Линейной комбинацией системы векторов \(v_1..., v_k\) пространства называется
- сумма вида \(\lambda_1 v_1+...+\lambda_k v_k\)  где \(\lambda_i\in k\)
- \(\sum_{i\in I}\lambda_i v_i\) с конечным числом скаляров \(\lambda_i\) (она тривиальна, если все коэффициенты \(\lambda _i\) равны нулю)
#+end_definition

#+begin_definition 
Линейная оболочка \(\{v_i:i\in I\}\) — множество всех линейных комбинаций системы.
Обозначается:
- \(\langle v_i:i\in I> \rangle\)
- \(\langle v_1, ..., v_k\rangle\)  (для конечных систем)
#+end_definition

#+begin_definition 
Система векторов \(\{v_i:i\in I\}\):
- Линейно зависимая, если есть \(\lambda_i\) где \[ ( \lambda_i \neq 0) \land \left(\sum_{i \in I} \lambda_i v_i = 0\right) \]
- Линейно независимая в обратном.

#+end_definition
#+begin_remark 
Линейная оболочка  \(\langle v_i:i\in I> \rangle\) является подпостранством в \(V\), притом, это наименьшее линейное подпространство включающее все векторы системы.
#+end_remark
#+begin_proof 
- Сумма векторов и умножение вектора системы на скаляр это линейные комбинации, принадлежащие линейной оболочке, соответственно \(\langle v_i:i\in I> \rangle\) — подпространство.
- Допустим, существует некое подпространство включающее векторы из \(\{v_i:i\in I\}\), выходит оно содержит все их линейные комбинации и \(\langle v_i:i\in I> \rangle\).
#+end_proof


