#+latex_class: russian
* Линейное пространство и подпространство 
k — основное поле
элементы поле k - скаляры.
** линейное пространство
#+begin_definition 
Линейное(векторное) пространство над полем k. Множество с двумя операциями "\(+\)" и "\(*\)".

\[+ : V\times V\to V (u, v)\to u+ v \] .
\[ *:V\times V\to V (u, v)\to u* v\]
#+end_definition
аксиомы, которые должны выполняться:
1. \( \forall u, v \in V \, (u + v = v + u) \)
2. \( \forall u, v, w \in V \, ((u + v) + w = u + (v + w)) \)
3. \( \exists 0 \in V \, \forall v \in V \, (v + 0 = v) \)
4. \( \forall v \in V \, \exists (-v) \in V \, (v + (-v) = 0) \)
5. \( \forall \lambda \in k \, \forall u, v \in V \, (\lambda \cdot (u + v) = \lambda \cdot u + \lambda \cdot v) \)
6. \( \forall \lambda, \mu \in k \, \forall v \in V \, ((\lambda + \mu) \cdot v = \lambda \cdot v + \mu \cdot v) \)
7. \( \forall \lambda, \mu \in k \, \forall v \in V \, (\lambda \cdot (\mu \cdot v) = (\lambda \mu) \cdot v) \)
8. \( \forall v \in V \, (1 \cdot v = v) \)

#+begin_prop 
\( \forall v, \lambda \in V \, (\mathbf{0}* v = \mathbf{0}*\lamba= \mathbf{0}) \)  
#+end_prop
#+begin_prop 
\( \forall v \in V \, ((-1) \cdot v = -v) \)
#+end_prop

#+begin_prop 
\( \forall \lambda \in k \, \forall v \in V \, ((\lambda \cdot v = \mathbf{0}) \implies (\lambda = 0 \lor v = \mathbf{0})) \)
#+end_prop
\\ доказывать не буду

#+begin_exam 
1. Множество {0}, состоящее из одного элемента 0, является линейным пространством над любым полем.
2. Множества векторов на прямой, на плоскости, в пространстве, являются линейными пространствами над полем \(\mathbb{R}\).
3. Поле k является векторным пространством над самим собой.
4. \(\mathbb{C}\) векторное пространство над \(\mathbb{R}\) , а \(\mathbb{R}\) на \(\mathbb{Q}\)
 \(k_1\subset k_2\)  подполе, то k_2 - векторное пространство над k_1 
5. n-мерное координатное(или арифметическое) пространство над k. \(n=1 \implies k^n=k\) [[arifmetics_space]]
6. \(k^{\mathbb{X}} =\{f: \mathbb{X}\to k\}\) \(\mathbb{X}\) - множество, \(k\) - поле.
   \((f+g)(x)=f(x)+g(x)\)
   \((\lambda * f)(x)=\lambda f(x)\)
   \(\mathbb{X}=\{1,2..., n\}\)
   \(k^{\mathbb{X}}=k^n\)
7. \(C(\mathbb{R})\subset \mathbb{R}^\mathbb{R}\) где C - непрерывная функция.
8. Множество решений однородной системы линейных уравнений
9. \(\mathbb{R}^{\infty}\) [[finite_sequence]], пространство \(\overset{\wedge}{\mathbb{R}}^{\infty }\) [[set_of_all_sequences]]
10. Множество \(k[x]\)  многочленов от одной переменной с коэффициентами в \(k\) являются линейными пространством. И множество \(k_n[x]\) степени не выше чем n.
11. Множество всех матриц размера \(m\times n\) с элементами из \(k\) образует линейное пространство \(\operatorname{Mat}_k(m, n)\) относительно операций сложения матриц и поэлементарного умножения матриц на числа. При \(m=1\) мы получаем пространство строк \(k^n\)
#+end_exam

#+name: finite_sequence
#+begin_definition 
финитная последовательность. (с конечным куском и после бесконечными нулями)

\(\mathbb{R}^{\infty}\)  - бесконечная последовательность \((x_1, x_2,...x_n)\) x_i=0 при \(i> N\) для некотого \(N\)
\(\mathbb{R}^{\infty}\equiv\bigcup_{n\geq0}\mathbb{R}^n\) 
#+end_definition

#+name: arifmetics_space
#+begin_definition 
n-мерное координатное(или арифметическое) пространство над k.
\(k^n:= \{(x_1,...,x_n):x_i\in K\}\) — множество последовательностей (строк) фиксированной длина n из элементов поля k.

к примеру \(\mathbb{R}^n\) и \(\mathbb{C}^n\)
#+end_definition

#+name: set_of_all_sequences
#+begin_definition 
\(\overset{\wedge}{\mathbb{R}}^{\infty }\) - множество всех последовательностей.
#+end_definition

** линейное подпространство 
#+begin_definition 
Множество \(W\subset V\) линейного пространства \(V\)  называется подпространством, если для любых векторов \(u, v \in W\)  и скаляра \(\lambda \in k\)  оно само является пространством.
соответственно выполняются эти аксиомы:
1) \(u+v\in W\)
2) \(\lambda u\in W\)
#+end_definition
#+begin_exam 
Вот некоторые примеры подпространств.
1. {0) является подпространством в любом пространстве V.
2. Множество векторов, коллинеарных заданному вектору, является подпространством в пространстве всех векторов на плоскости или в пространстве.
3. Пространство \(C(\mathbb{R})\) непрерывных функций является подпространством в пространстве \(\mathbb{R}^{\mathbb{R}}\) всех функций на \(\mathbb{R}\).
4. Пространство \(\mathbb{R}^\infty^{}\) финитных последовательностей является подпространством в пространстве \(\overset{\wedge}{\mathbb{R}}^\infty\) всех последовательностей.
5. \(k_n[x]\) является подпространством \(k_m[x]\) при \(m\geq n\), а также в \(k[x]\).
#+end_exam
* линейная зависимость, базис, размерность
Пусть \(V\) — линейное пространство над полем k.
#+begin_definition 
Линейной комбинацией конечной системы векторов  \(v_1..., v_k\) пространства называется формальная сумма вида сумма вида \(\lambda_1 v_1+...+\lambda_k v_k\)  где \(\lambda_i\in k\).

Представляет вектор \(v=\lambda_1 v_1+...+\lambda_k v_k\) 
#+end_definition
#+begin_exam 
\(\mathbb{R}^3\)

\(z(1,0,0)+(-z)(0,1,0)+z(-1,1,0)\)

\(0(1,0,0)+0(0,1,0)+0(-1,1,0)\)

Представляет вектор \(\vec{0}=(0,0,0)\)
#+end_exam

#+begin_definition 
Линейная комбинация бесконечной системы векторов.
\(\{v_i:i\in \mathbb{I}\}\) - сумма вида \(\underset{_{i\in I}}{\sum}\lambda_i v_i\) с конечным числом скаляров \(\lambda_i\) отличных от нуля.
Линейная комбинация — это функция \(\mathbb{I}\to K\) \(i\to \lambda_i\)

С конечным носителем(принимает ненулевые значения только на конечном подмножестве индекса)
#+end_definition

#+begin_definition 
Система векторов \(\{v_i:i\in \mathbb{I}\}\) линейно зависимая, если есть \(\lambda_i\) где \[ ( \lambda_i \neq 0) \land (\sum_{i \in I} \lambda_i v_i = \vec{0}) \]  и линейно независимая в обратном.
#+end_definition

#+begin_definition 
Линейная оболочка \(\{v_i:i\in I\}\) — подмножество векторов \(\mathbb{V}\) представляемых линейными комбинациями \(\underset{i\in \mathbb{I}}{\sum}\lambda_iv_I\). 

Обозначается \(\langle v_i:i\in \mathbb{I} \rangle\) или \(\langle v_1, ..., v_k\rangle\)  (для конечных систем)
#+end_definition

#+begin_prop 
Линейная оболочка  \(\langle v_i:i\in \mathbb{I} \rangle\) является подпостранством в \(V\), притом, это наименьшее линейное подпространство включающее все векторы системы.
#+end_prop

#+begin_proof 
- Сумма векторов и умножение вектора системы на скаляр это линейные комбинации, принадлежащие линейной оболочке, соответственно \(\langle v_i:i\in I> \rangle\) — подпространство.
- Допустим, существует некое подпространство включающее векторы из \(\{v_i:i\in I\}\), выходит оно содержит все их линейные комбинации и \(\langle v_i:i\in I> \rangle\).
#+end_proof

