#+latex_class: russian

Использованная, помимо лекций, литература:

Зорич В. А. Математический анализ. Часть I. — Изд. 10-е, испр. — М.: МЦНМО,

Теория множеств:
    Set Theory for the Working Mathematician/ Krzysztof Ciesielski
    [[https://people.maths.ox.ac.uk/~knight/lectures/b1st.html]]
* Общематематические понятия и обозначения
** в основном про логические обозначения
=Если обозначение удобны для открытий..., то поразительным образом сокращается работа мысли.=
Г. Лейбниц(1646-1716)

Логическая символика
| знак           | значение                                                         |
|----------------+------------------------------------------------------------------|
| \(\neg\)          | отрицание                                                        |
| \(\land\)          | конъюкция, союз и                                                |
| \(\lor\)          | дизъюнкция                                                       |
| \(\implies \)  | влечёт                                                           |
| $A \implies B$ | B следует из A, B необходимый признак для A, A достаточный для B |
| \(\iff \)      | тождественно равно                                               |
|   \(\equiv\)                |                            равно по определению               |
| \(\exists\)          | квантор существования                                            |
| \(\forall\)          | квантор общности                                                 |
| \(:=\)         | со стороны определяемого понятия                                 |
| \(\exists !\)        | единственное существующее                                        |

> начало и конец докозательства < 

| Приоритет символов: |
|---------------------|
| \(\neg\)               |
| \(\cap\)               |
| \(\cup\)               |
| \(\implies\)        |
| \(\iff\)            |

#+begin_definition
 $$A\iff B$$

\((A\implies B)\cap (B\implies A)\)
при док-ве равносильности:
1) \(A\implies B\) необходимость В при необходимости А
2) \(B\implies A\) достаточность В для А
#+end_definition

#+begin_remark 
некоторые сокращения:
\((\forall x\in \mathbb{X}) P:=\forall x(x\in \mathbb{X}\to P(x))\)
\((\exists x\in \mathbb{X}) P:=\exists x(x\in \mathbb{X}\land P(x))\)
\((\forall x> a) P:=\forall x(x\in  \mathbb{R} \land x> a\to P(x))\)
\((\exists x > a) P:=\exists x(x\in \mathbb{R} \land x > a\land P(x))\)
#+end_remark

** Насчёт  множеств
С конца XIX — начала XX столетия наиболее универсальным языком математики стал язык теории множеств.

создатель теоретико-множественного языка математики и теории бесконечных множеств Георг Кантор (1845-1918)

#+begin_definition 
Под множеством мы понимаем объединение в одно целое определенных, вполне различимых объектов нашей интуиции или нашей мысли.
#+end_definition

В Картеровской "наивной" теории множеств:
1. множество может состоять из любых различимых объектов.
2. множество однозначно определяется набором составляющих объектов.
3. любое свойство может определять множество объектов.
   
*** обозначения 
Способы задания множеств:
1. Словесный
2. Перечисление эл-тов \(\mathbb{A}=\{1, 2, 3\}\)
3. Через указание характеристического свойства  \(P(x)\) \(\mathbb{A}=\{x|P(x)\}\)
4. Специальный, он используется для обозначения числовых промежутков и числовых множеств.

Если x — объект, P — свойство, \(P(x)\)  — x обладает свойством P.
\(\{x|P(x)\}\) множество обладающих свойством x.

#+begin_definition 
Элемент множества — это объект, который принадлежит множество. \(a\in \mathbb{A}\)
\(x\in \mathbb{X}\) - элемент множества

\(x\neg \in \mathbb{X}\)  или \(x\notin \mathbb{X}\) - не элемент множества

#+end_definition
#+begin_definition 
\(\forall x((x\in A)\iff(x\in B))\) означает \(A=B\)
#+end_definition

#+begin_definition 
Если любой элемент А является элементом множества В, то пишут \(A\subset B\) и говорят что А является подмножеством В.

Отношение включения:
\((A\subset B):=\forall x((x\in A)\implies (x\in B))\)

Если \(A\subset B\) и \(A\neq B\) то включение строгое и А собственное множество В.
#+end_definition

#+begin_definition 

Если М — множество, то любое свойство Р выделяет в подмножество М те элементы которые обладают этим свойством: \(\{ x\in M|P(x)\ }\)

=>

\[M=\{x\in M|x\in M\}\]

#+end_definition
#+begin_remark 
если же взять свойство, которому не соответствует ни один элемент из множества

\[\varnothing =\{x\in M|x\neq x\}\]

\(A=B \iff\{x\in A | (x\in A)\iff (x\in B)\}\)

получится пустое множество
#+end_remark
*** операции над множествами
1. объединение множеств A и B:
   #+begin_definition 
    \(A\cup B:=\{x|(x\in A)\lor (x \in B)\}\)
   #+end_definition 
   #+begin_definition 
 дизъюнктивное объединение А и В:
   Объединение непересекающихся подможеств \(\mathbb{A}\sqcup \mathbb{B}\) 
   #+end_definition 
2. пересечение множеств A и B:
   #+begin_definition 
    \(A\cap B :=\{x|(x\in A)\land (x\in B)\}\)
   #+end_definition 
3. разность множества
   #+begin_definition 
    \(A\setminus B:=\{x|(x\in A), \land (x\notin B)\}\)
   #+end_definition 

   Разность между множеством М и содержащимся в нём подмножеством А обычно называют А в М и обозначают через \[C_M A\] или \[CA\] если понятно к какому множеству дополнение.

   - Пример. Плавила де Моргана:
      \[C_M(A\cup B)=C_MA\cap C_MB\]
      
      \[C_M(A\cap B)=C_MA\cup C_MB\]
      докажем первое из равенств
   #+begin_proof 
      \((x\in C_M(A\cup B))\implies 
      (x\notin (A\cup B)) \implies
      ((x\notin A)\land (x\notin B)) \implies (x\in C_MA)\land (x\in C_M B)\implies (x\in(C_MA\cap C_MB)) \)

      \[C_M(A\cup B)\subset C_MA\cap C_MB\]
      
      \((x\in (C_MA\cap C_M B)) \implies ((x\in C_MA)\land (x\in C_MB))\implies ((x\notin A)\land (x\notin B)) \implies (x\notin (A\cup B)) \implies (x\in C_M(A\cup B)) \)
      
      \[(C_MA\cap C_M B)\subset C_M(A\cup B)\]
   #+end_proof
4. Прямое (декартово) произведение множеств.

   Для любой пары двух множеств можно образовать новое множество \[\{A, B\}=\{B, A\}\]  элементами которого являются только они. Множество состоит из двух эл-тов если множ-ва не равны и одного в обратном случае.
    #+begin_definition 
   Существует так же упорядоченная пара
   \[(A, B)=(C, D) \]  где \[A=C\] \[ B=D\]

   \[A\neq B \implies (A, B)\neq (B, A)\]
    #+end_definition
   Пусть, X и Y — произвольные множества. То это прямое произведение:
   #+begin_definition 
   \[\mathbb{X}\times \mathbb{Y} := \{(x, y) |(x \in \mathbb{X}) \land (y\in \mathbb{Y})\}\]
   #+end_definition

   для \(\mathbb{A}_n\) множеств.
   \(A_1 \times A_2 \times ... \times A_n = \{ (a_1, a_2, ..., a_n) | a_i \in A_i \}\)
   декартово произведение:
   \( \mathbb{A}\times \mathbb{A}=\mathbb{A}^2\)
   
   Образованное всеми упорядоченными парами (x, y) первый член которых есть элемент из Х, а второй член — элемент из Y, называется прямым или декартовым произведением множеств X и Y.
   
   \[X\neq Y \implies X\times Y\neq Y\times X\]
   
   #+begin_remark 
   известная всем система декартовых координат превращает эту плоскость в произведения числовых осей.
   #+end_remark
*** свойство операций  над множествами
| Свойство         | Символьно                                         |
|------------------+---------------------------------------------------|
| Коммутативность  | $\mathbb{A}\cup \mathbb{B}=\mathbb{B}\cup \mathbb{A}$ |
|                  | $\mathbb{A}\cap \mathbb{B}=\mathbb{B}\cap \mathbb{A}$ |
| Ассоциативность  | $A\cup (B\cup C)=(A\cup B)\cup C$                           |
| Дистрибутивность | $A\cup(B\cap C)=(A\cup B)\cap(A\cup C)$                        |
|                  | $A\cap(B\cup C)=(A\cap B)\cup(A\cap C)$                        |
| Идемпонтность    | $A\cup A=A$                                        |
|                  | $A\cap A=A$                                        |
|                  |                                                   |
|                  | $A\cup \varnothing = A$                            |
|                  | $A\cap \varnothing = A$                            |
** Парадокс Рассела (1872-1970)
#+begin_prop 


К множество всех множеств
\(p(K)\) - множество не содержит себя в качестве своего элемента
#+end_prop
#+begin_proof 

\(K={M|P(M)}\)

\(K\in K\implies \neg P(k)\implies K\notin K\)

\(K\notin K \implies P(k)\implies K\in K\)
#+end_proof

В современной математике понятие множества вносится аксиоматически.

Множество обладает определённым набором свойств, описание этих свойств составляет всю аксиоматику.

В рамках этих аксиом множество всех множеств не является множеством.

** Аксиоматика теории множеств
#+begin_axiom 
Аксиома объёмности (The Axiom of Extension)
Множества равны тогда и только тогда, когда имеют одни и те же элементы.
\[A = B \iff \forall x((x \in A) \iff (x \in B))\]
#+end_axiom

#+begin_axiom 
Аксиома выделения (Comprehension Scheme)
Любому множеству \(A\) и свойству \(P\) отвечает множество \(B\), элементы которого суть те элементы множества \(A\), которые обладают свойством \(P\).
\[B = \{x \in A \mid P(x)\}\]
Из этой аксиомы следует, что разность множеств, в том числе дополнение, являются множествами.
#+end_axiom

#+begin_axiom 
Аксиома пустого множества (Empty Set Axiom)
Существует пустое множество.
\[\varnothing = \{x \in X \mid x \neq x\}\]
Учитывая аксиому объёмности, пустое множество единственно.
#+end_axiom

#+begin_axiom 
Аксиома объединения (Axiom of Union)
Для каждого семейства \(\mathbb{M}\) существует множество, которое является объединением \(\bigcup \mathbb{M}\), содержащим все элементы из \(\mathbb{M}\):
\[x \in \bigcup \mathbb{M} \iff \exists X((X \in \mathbb{M}) \land (x \in X))\]
Эта аксиома позволяет определить пересечение семейства множеств как множество:
\[\bigcap \mathbb{M} := \{x \in \bigcup \mathbb{M} \mid \forall X((X \in \mathbb{M}) \implies (x \in X))\}\]
#+end_axiom

#+begin_axiom 
Аксиома пары (Pairing Axiom)
Для любых множеств \(X\) и \(Y\) существует множество \(Z\), которое содержит в точности элементы этих множеств:
\[\{X, Y\} = Z\]
Если множества равны, то \(Z\) состоит из одного элемента. Эта аксиома помогает ввести упорядоченную пару:
\[(X, Y) := \{\{X\}, \{X, Y\}\}\]
#+end_axiom

#+begin_axiom 
Аксиома множества подмножеств (Power Set Axiom)
Для каждого множества \(X\) существует множество \(\mathcal{P}(X)\), состоящее из всех подмножеств \(X\):
\[\mathcal{P}(X) = \{Y \mid Y \subset X\}\]
Так можно ввести прямое произведение множеств:
\[X \times Y := \{p \in \mathcal{P}(\mathcal{P}(X) \cup \mathcal{P}(Y)) \mid p = (x, y) \land (x \in X) \land (y \in Y)\}\]
#+end_axiom

#+begin_axiom 
Аксиома бесконечности (Infinity Axiom)
Введём понятие последователя: \(X^+ = X \cup \{X\}\) (добавляет к множеству одноэлементное множество \(\{X\}\)).

Назовём множество индуктивным, если оно содержит пустое множество и последователь каждого своего элемента.

Аксиома утверждает, что индуктивные множества существуют:
\[\exists X(\varnothing \in X \land \forall y(y \in X \to y \cup \{y\} \in X))\]

Аксиома позволяет определить модель множества \(\mathbb{N}_0\) натуральных чисел как пересечение всех индуктивных множеств, т. е. наименьшее индуктивное множество. Его элементами являются:
\[\varnothing, \varnothing^+ = \varnothing \cup \{\varnothing\} = \{\varnothing\}, \{\varnothing\}^+ = \{\varnothing\} \cup \{\{\varnothing\}\}, \ldots\]
#+end_axiom

#+begin_axiom 
Аксиома подстановки (Replacement Axiom)
Для любого множества \(X\), любого набора множеств \((N_i)_{i=1}^n\) и любого закона \(\Phi\), который каждому \(x \in X\) и каждой последовательности \((N_1, \ldots, N_n)\) ставит в соответствие единственное множество \(\Phi(x, N_1, \ldots, N_n)\), существует множество:
\[\{y \mid \exists x \in X: y = \Phi(x, N_1, \ldots, N_n)\}\]
#+end_axiom

#+begin_axiom 
Аксиома выбора (Axiom of Choice)
Для каждого семейства непустых попарно непересекающихся множеств существует множество \(C\) такое, что для любого множества \(X\) из данного семейства множество \(X \cap C\) состоит ровно из одного элемента.
#+end_axiom
** вкратце о числах 
\(\mathbb{N}=\{1, 2, 3, ...\}\) 
\(\mathbb{Z}=\{0, \pm 1, \pm 2, ...\}\)
\(\mathbb{Q}=\{\frac{p}{q}|p\in \mathbb{Z}\land q\in \mathbb{N}\}\)

Любое рац число может быть записанно в виде конечной дроби, либо периодической дроби.

\(\sqrt{2}\notin \mathbb{Q}\)

геометрическая интерпретация множества действительных чисел.

введение таких точек на прамой L взаимоодназначное соответствие между точками и множеством R. Направление задаваемое лучом с вершиной в точке ноль и содержащим 1 является положительным.


\(\forall x\in \phi \exists ! x\in \mathbb{R}\)
x  длина отрезка икс

x - Длина положительная ОХ, если икс лежит правее 0.

х - длина отрезка ОХ отрицательная, если Х правее.

Такую прямую для которой установлено взаимооднозначное соответствие с R, называют числовой(координатной осью)

При рассмотрении числовых множеств(подможеств R действительных) принято использовать геом-кий язык.
** Обозначение некоторых числовых множеств
\(a\in \mathbb{R}, b\in \mathbb{R}, a<b\)
#+begin_definition 
ограниченные числовые промежутки.:
    \([a,b]=\{x\in \mathbb{R}|a\leq x\leq b\}\) отрезок
    \((a, b)=\{x\in \mathbb{R}|a<x<b\}\)  интервал
    \((a, b]=\{x\in \mathbb{R}|a<x\leq b\}\) полуинтервал
    \([a, b)=\{x\in \mathbb{R}|a\leq x<b\}\) полуинтервал

#+end_definition

#+begin_definition 
неограниченные числовые промежутки:

    \((- \infty ,a ) =\{x\in \mathbb{R}|x<a\}\)
    \((- \infty ;a ] =\{x\in \mathbb{R}|x\leq a\}\)
    \((a,+ \infty  ) =\{x\in \mathbb{R}|x> a\}\)
    \([a,+ \infty  ) =\{x\in \mathbb{R}|x\geq a\}\)
\((-\infty, + \infty)= \mathbb{R}\)
#+end_definition
#+begin_remark 
\((a,b)=\{x\in \mathbb{R}|a<x<b|\}\)
\(\{a, b\}\) - множество из a, b
#+end_remark

#+begin_definition 
Расширенная числовая прямая, или проективно рассширенная:
\(\widehat{\mathbb{R}}=\mathbb{R} \cup \{\infty\}\)
#+end_definition

#+begin_definition 
Аффинно расширенная бесконечность:
\(\overline{\mathbb{R}} = \mathbb{R} \cup \{-\infty, +\infty\} = [-\infty, +\infty]\)
#+end_definition
** мощность множества
Пусть А и В - два конечных множества. \(A=\{a, b, c, d, ...\}\) \(B=\{\alpha, \beta, \gamma, \delta, ...\}\)

Одинаково или нет количество элементов в этих множествах можно решить не считая их элементы, а устанавливая соответствия. Для этого способа сравнения хар-но то, что для каждого эле-та одного множества указывается один и только один эл-т другого мн-ва. 

#+begin_definition 
    Пусть Х и У - два множества.
    
    Правило \(\phi\) которое каждому эл-ту х из множества Х ставит в соответствие один и только один элемент у из множества У причём, каждый элемент у из У оказывается соотнесённый только одному х из множества Х, называется взаимно однозначным соответствием между множествами Х и У.
    
Замечание, взаимно однозначное соответствие носит название биективное отображение. Биекция.

Если между множествами \(\mathbb{A}\) и \(\mathbb{B}\)(не обязательно конечными) можно установить взаимно однозначное соответствия, то такие мно-ва называются экви-ми или равно мощными.

\(A\sim B\)
#+end_definition

отношение равномощности разбивает соотножение на классы эквивалентных множ-в

Множества одного класса эквивалентности имеют одинаковое количество элементов(равномощных)

#+begin_definition 
Класс которому принадлежит мно-во Х, называется мощностью множества Х или кардинальным числом(кардиналом) множества Х и обозначается \(\text{Card }\mathbb{X}\).

если \(\mathbb{X}\sim \mathbb{Y}\) то пишут \(\text{Card} \mathbb{X}=\text{Card}\mathbb{Y}\)
#+end_definition
#+begin_remark 
Если берём \(\mathbb{X}\in \mathbb{Y}\) то \(\text{Card} \mathbb{X}<\text{Card} \mathbb{Y}\)
#+end_remark

такой способ определения мощности можно использовать и для бесконечных множеств
#+begin_exam 
 \(\mathbb{N}=\{1, 2,..\}\)
   \(M=\{2n|n\in \mathbb{N}\}\)
   \(M\in N\)
   \(\text{Card} \mathbb{M}=\text{Card} \mathbb{N}\)
#+end_exam
#+begin_definition 
Все бесконечные множества для которых может быть установлено взаим-одн соответвие с множеством натуральных чисел называются счётными.
#+end_definition
#+begin_remark 
Все эл-ты счётных множеств могут быть занумерованы в ин-ти последовательность
#+end_remark

Для бесконечных множеств возможна ситуация когда одно является подмножеством другого, при этом оба равно мощные. 

   \( \mathbb{N}=\alpha\)
   
   \((0,1)\) - не счётное
   > допустим оно счётное, если это так, то мы можем их занумеровать
   но так не получится, потому что можно сделать наискосок новые индексы. <

   \(\text{Card}(a, b)=c = \text{Card}\ \mathbb{R}=c\)
   \(x\to \frac{x}{1-|x|}\)  f устанавливае взаи-одн соответствие между (0, 1) и R  
   
** Функция
Пусть \(\mathbb{X},\ \mathbb{Y}\) — два числовых множества.
\(\mathbb{X}\subset\mathbb{R}, \mathbb{Y}\subset\mathbb{R}\)

#+begin_definition
Говорят, что есть функция *f*, определённая на множестве X со значениями в множестве Y, если определён закон (правило, зависимость), по которому каждому элементу из множества X ставится в соответствие единственный элемент из Y.

\(f:\mathbb{X}\to\mathbb{Y}\)
\(\mathbb{X}\) — область определения функции f
\(x\in\mathbb{X}\) — независимая переменная, аргумент функции.
#+end_definition

Множество всех значений функции будем называть множеством значений или областью значений функции.

\(f(\mathbb{X})=\{y\in \mathbb{Y}|\ \exists x((x\in \mathbb{X})\land y=f(x))\}\)
\(y\) — зависимая переменная, \(y=f(x)\)

#+begin_definition
Если \(B\subset f(\mathbb{X})\) и \(f(\mathbb{X})=B\), то \(f^{-1}(B)=\mathbb{X}\) — прообраз множества \(B\).
#+end_definition

| Свойства отображений (функций)                                                               |
|----------------------------------------------------------------------------------------------|
| Название          | Условие                                                                                      |
|-------------------+----------------------------------------------------------------------------------------------|
| Сюръекция         | \(f(\mathbb{X})=\mathbb{Y}\) (каждый элемент \(y\) имеет прообраз в \(\mathbb{X}\))             |
| Инъекция          | \(x_1 \neq x_2 \implies f(x_1) \neq f(x_2)\) (разным аргументам соответствуют разные значения) |
| Биекция           | Отображение является и сюръективным, и инъективным                                            |

#+begin_remark
Для того, чтобы аналитическое выражение \(f(x)=x^2\) являлось биективным, надо его ограничить (например, рассмотреть на \(\mathbb{R}_+\)).
#+end_remark

#+begin_remark
Если отображение \(f:\mathbb{X}\to \mathbb{Y}\) биективно, то возникает отображение \(f^{-1}:\mathbb{Y}\to \mathbb{X}\), которое каждому элементу \(y\) из множества \(\mathbb{Y}\) ставит в соответствие элемент \(x\) из множества \(\mathbb{X}\) такой, что \(f(x)=y\). Это отображение называют *обратным отображением* для \(f\).
#+end_remark

#+begin_remark
Свойство двух отображений быть обратными является взаимным.
#+end_remark

* Действительные(вещественные) числа
** Аксиоматическое определение действительных чисел
#+begin_definition 
Множество \(\mathbb{R}\) называется *множеством действительных (вещественных) чисел*, а его элементы — *действительными (вещественными) числами*, если выполнены следующие группы аксиом:
#+end_definition
*** (I) Аксиомы сложения
#+name: ax-add-comm
#+begin_axiom 

Коммутативность сложения
\(\forall a,b \in \mathbb{R}: a + b = b + a\)
#+end_axiom

#+name: ax-add-assoc
#+begin_axiom 

Ассоциативность сложения
\(\forall a,b,c \in \mathbb{R}: (a + b) + c = a + (b + c)\)
#+end_axiom

#+name: ax-add-zero
#+begin_axiom 

Нейтральный элемент сложения
\(\exists 0 \in \mathbb{R}: \forall a \in \mathbb{R}: a + 0 = a\)
#+end_axiom

#+name: ax-add-inv
#+begin_axiom 

Противоположный элемент
\(\forall a \in \mathbb{R}\ \exists (-a) \in \mathbb{R}: a + (-a) = 0\)
#+end_axiom

*** (II) Аксиомы умножения
#+name: ax-mul-comm
#+begin_axiom 

Коммутативность умножения
\(\forall a,b \in \mathbb{R}: a \cdot b = b \cdot a\)
#+end_axiom

#+name: ax-mul-assoc
#+begin_axiom 

Ассоциативность умножения
\(\forall a,b,c \in \mathbb{R}: (a \cdot b) \cdot c = a \cdot (b \cdot c)\)
#+end_axiom

#+name: ax-mul-one
#+begin_axiom 

Нейтральный элемент умножения
\(\exists 1 \in \mathbb{R}\ (1 \neq 0): \forall a \in \mathbb{R}: a \cdot 1 = a\)
#+end_axiom

#+name: ax-mul-inv
#+begin_axiom 

Обратный элемент
\(\forall a \in \mathbb{R}\ (a \neq 0)\ \exists a^{-1} \in \mathbb{R}: a \cdot a^{-1} = 1\)
#+end_axiom

*** (I, II) Аксиома дистрибутивности
#+name: ax-distrib
#+begin_axiom 

Дистрибутивность
\(\forall a,b,c \in \mathbb{R}: a \cdot (b + c) = a \cdot b + a \cdot c\)
#+end_axiom

*** (III) Аксиомы порядка
#+name: ax-order-refl
#+begin_axiom 

Рефлексивность
\(\forall x \in \mathbb{R}: x \leq x\)
#+end_axiom

#+name: ax-order-antisym
#+begin_axiom 

Антисимметричность
\((x \leq y) \land (y \leq x) \Rightarrow x = y\)
#+end_axiom

#+name: ax-order-trans
#+begin_axiom
Транзитивность
\((x \leq y) \land (y \leq z) \Rightarrow x \leq z\)
#+end_axiom

#+name: ax-order-total
#+begin_axiom
Линейная упорядоченность
\(\forall x,y \in \mathbb{R}: (x \leq y) \lor (y \leq x)\)
#+end_axiom

#+begin_definition 
Множество, удовлетворяющее аксиомам [[ax-order-refl]]-[[ax-order-trans]], называется *частично упорядоченным*, а множество, удовлетворяющее также аксиоме [[ax-order-total]], называется *линейно упорядоченным*.
#+end_definition

*** (I, III) Связь сложения и порядка
#+name: ax-add-order
#+begin_axiom 

Монотонность сложения
\(\forall x,y,z \in \mathbb{R}: (x \leq y) \Rightarrow (x + z \leq y + z)\)
#+end_axiom

*** (II, III) Связь умножения и порядка
#+name: ax-mul-order
#+begin_axiom 

Монотонность умножения
\(\forall x,y \in \mathbb{R}: (0 \leq x) \land (0 \leq y) \Rightarrow (0 \leq x \cdot y)\)
#+end_axiom

*** (IV) Аксиома полноты (непрерывности)
#+name: ax-completeness
#+begin_axiom 

Аксиома полноты
Если \(\mathbb{X}\) и \(\mathbb{Y}\) — непустые подмножества \(\mathbb{R}\) такие, что
\[
\forall x \in \mathbb{X},\ \forall y \in \mathbb{Y}: x \leq y,
\]
то
\[
\exists c \in \mathbb{R}: \forall x \in \mathbb{X},\ \forall y \in \mathbb{Y}: x \leq c \leq y
\]
#+end_axiom

*** Вопросы насчёт аксиоматики
Относительно данной системы аксиом возникают как минимум два фундаментальных вопроса:
1) Её непротиворечивость.
2) Может ли данная система аксиом однозначно определить математический объект, категорична ли система аксиом (с точностью до изоморфизма).

** Некоторые следствия
*** Следствия аксиом сложения
#+begin_corollary
В множестве действительных чисел имеется только один нуль.
#+end_corollary
#+begin_proof
Если \(0_1\) и \(0_2\) — нули в \(\mathbb{R}\), то по [[ax-add-zero]]:
\[0_1 = 0_1 + 0_2 = 0_2 + 0_1 = 0_2.\]
#+end_proof

#+begin_corollary
В множестве действительных чисел у каждого элемента имеется единственный противоположный элемент.
#+end_corollary
#+begin_proof
Если \(x_1\) и \(x_2\) — элементы, противоположные \(x \in \mathbb{R}\), то:
\[x_1 = x_1 + 0 = x_1 + (x + x_2) = (x_1 + x) + x_2 = 0 + x_2 = x_2.\]
Здесь последовательно использованы: [[ax-add-zero]], [[ax-add-inv]], [[ax-add-assoc]], [[ax-add-inv]] и снова [[ax-add-zero]].
#+end_proof

#+begin_corollary
Уравнение \(a + x = b\) в \(\mathbb{R}\) имеет единственное решение:
\[x = b + (-a).\]
#+end_corollary
#+begin_proof
Это следует из [[ax-add-inv]]:
\[
(a + x = b) \iff ((x + a) + (-a) = b + (-a)) \iff
\]
\[
\iff (x + (a + (-a)) = b + (-a)) \iff (x + 0 = b + (-a)) \iff (x = b + (-a)).
\]
Выражение \(b + (-a)\) обычно записывается как \(b - a\).
#+end_proof

*** Следствия аксиом умножения
#+begin_corollary
В множестве действительных чисел имеется только одна единица.
#+end_corollary
#+begin_proof
Доказательство аналогично доказательству единственности нуля (с заменой сложения на умножение и использованием [[ax-mul-one]]).
#+end_proof

#+begin_corollary
Для каждого числа \(x \neq 0\) имеется только один обратный элемент \(x^{-1}\).
#+end_corollary
#+begin_proof
Доказательство аналогично доказательству единственности противоположного элемента (с заменой сложения на умножение и использованием [[ax-mul-inv]]).
#+end_proof

#+begin_corollary
Уравнение \(a \cdot x = b\) при \(a \in \mathbb{R} \setminus 0\) имеет единственное решение:
\[x = b \cdot a^{-1}.\]
#+end_corollary
#+begin_proof
Доказательство аналогично доказательству для уравнения \(a + x = b\) (с заменой сложения на умножение и использованием [[ax-mul-inv]]).
#+end_proof

*** Следствия аксиомы связи сложения и умножения
#+begin_corollary
Для любого \(x \in \mathbb{R}\):
\[x \cdot 0 = 0 \cdot x = 0.\]
#+end_corollary
#+begin_proof
\[
x \cdot 0 = x \cdot (0 + 0) = x \cdot 0 + x \cdot 0 \Rightarrow
\]
\[
\Rightarrow x \cdot 0 = x \cdot 0 + (-(x \cdot 0)) = 0.
\]
Использованы [[ax-add-zero]], [[ax-distrib]] и [[ax-add-inv]].
#+end_proof

#+begin_corollary
\[(x \cdot y = 0) \Rightarrow (x = 0) \lor (y = 0).\]
#+end_corollary
#+begin_proof
Если, например, \(y \neq 0\), то из единственности решения уравнения \(x \cdot y = 0\) относительно \(x\) находим:
\[x = 0 \cdot y^{-1} = 0.\]
Использованы [[ax-mul-inv]] и предыдущее следствие.
#+end_proof

#+begin_corollary
Для любого \(x \in \mathbb{R}\):
\[-x = (-1) \cdot x.\]
#+end_corollary
#+begin_proof
\[
x + (-1) \cdot x = (1 + (-1)) \cdot x = 0 \cdot x = x \cdot 0 = 0,
\]
и утверждение следует из [[ax-add-inv]].
#+end_proof

#+begin_corollary
Для любого числа \(x \in \mathbb{R}\):
\[(-1)(-x) = x.\]
#+end_corollary
#+begin_proof
Следует из предыдущего следствия и единственности элемента \(x\), противоположного \(-x\).
#+end_proof

#+begin_corollary
Для любого числа \(x \in \mathbb{R}\):
\[(-x)(-x) = x \cdot x.\]
#+end_corollary
#+begin_proof
\[
(-x)(-x) = ((-1) \cdot x)(-x) = (x \cdot (-1))(-x) = x((-1)(-x)) = x \cdot x.
\]
Здесь последовательно использованы: предыдущие следствия, [[ax-mul-comm]] и [[ax-mul-assoc]].
#+end_proof

*** Следствия аксиом порядка
#+begin_corollary
\(\forall x, y \in \mathbb{R}\) справедливо одно из трёх соотношений:
\[x < y, \quad x = y, \quad x > y.\]
#+end_corollary
#+begin_proof
Следует из [[ax-order-antisym]] и [[ax-order-total]] 
#+end_proof

#+begin_corollary 
\(\forall x, y, x\in \mathbb{R}\)

\((x<y)\land (y\leq z)\implies (x< z)\)
\((x\leq y)\land (y < z)\implies (x< z)\)
#+end_corollary

