#+latex_class: russian

Использованная, помимо лекций, литература:

Зорич В. А. Математический анализ. Часть I. — Изд. 10-е, испр. — М.: МЦНМО,

Теория множеств:
    Set Theory for the Working Mathematician/ Krzysztof Ciesielski
    [[https://people.maths.ox.ac.uk/~knight/lectures/b1st.html]]

* в основном про логические обозначения
=Если обозначение удобны для открытий..., то поразительным образом сокращается работа мысли.=
Г. Лейбниц(1646-1716)

Логическая символика
| знак           | значение                                                         |
|----------------+------------------------------------------------------------------|
| \(\neg\)          | отрицание                                                        |
| \(\land\)          | конъюкция, союз и                                                |
| \(\lor\)          | дизъюнкция                                                       |
| \(\implies \)  | влечёт                                                           |
| $A \implies B$ | B следует из A, B необходимый признак для A, A достаточный для B |
| \(\iff \)      | тождественно равно                                               |
|   \(\equiv\)                |                            равно по определению               |
| \(\exists\)          | квантор существования                                            |
| \(\forall\)          | квантор общности                                                 |
| \(:=\)         | со стороны определяемого понятия                                 |
| \(\exists !\)        | единственное существующее                                        |

> начало и конец докозательства < 

| Приоритет символов: |
|---------------------|
| \(\neg\)               |
| \(\cap\)               |
| \(\cup\)               |
| \(\implies\)        |
| \(\iff\)            |

#+begin_proof
 $$A\iff B$$

\((A\implies B)\cap (B\implies A)\)
при док-ве равносильности:
1) \(A\implies B\) необходимость В при необходимости А
2) \(B\implies A\) достаточность В для А
#+end_proof

#+latex: \newpage
* Насчёт  множеств
С конца XIX — начала XX столетия наиболее универсальным языком математики стал язык теории множеств.

создатель теоретико-множественного языка математики и теории бесконечных множеств Георг Кантор (1845-1918)

#+begin_definition 
Под множеством мы понимаем объединение в одно целое определенных, вполне различимых объектов нашей интуиции или нашей мысли.
#+end_definition

В Картеровской "наивной" теории множеств:
1. множество может состоять из любых различимых объектов.
2. множество однозначно определяется набором составляющих объектов.
3. любое свойство может определять множество объектов.
   
** обозначения 
Способы задания множеств:
1. Словесный
2. Перечисление эл-тов \(\mathbb{A}=\{1, 2, 3\}\)
3. Через указание характеристического свойства  \(P(x)\) \(\mathbb{A}=\{x|P(x)\}\)
4. Специальный, он используется для обозначения числовых промежутков и числовых множеств.

Если x — объект, P — свойство, \(P(x)\)  — x обладает свойством P.
\(\{x|P(x)\}\) множество обладающих свойством x.

Элемент множества — это объект, который принадлежит множество. \(a\in \mathbb{A}\)
\(x\in \mathbb{X}\) - элемент множества

\(x\neg \in \mathbb{X}\)  или \(x\notin \mathbb{X}\) - не элемент множества

\(\forall x((x\in A)\iff(x\in B))\) означает \(A=B\)

Если любой элемент А является элементом множества В, то пишут \(A\subset B\) и говорят что А является подмножеством В.

Отношение включения:
\((A\subset B):=\forall x((x\in A)\implies (x\in B))\)

Если \(A\subset B\) и \(A\neq B\) то включение строгое и А собственное множество В.

Если М — множество, то любое свойство Р выделяет в подмножество М те элементы которые обладают этим свойством:
\[\{x\in M|P(x)\}\]

=>

\[M=\{x\in M|x\in M\}\]

если же взять свойство, которому не соответствует ни один элемент из множества

\[\varnothing =\{x\in M|x\neq x\}\]

\(A=B \iff\{x\in A | (x\in A)\iff (x\in B)\}\)

получится пустое множество
** операции над множествами
1. объединение множеств A и B:
    \(A\cup B:=\{x|(x\in A)\lor (x \in B)\}\)
 дизъюнктивное объединение А и В:
   Объединение непересекающихся подможеств \(\mathbb{A}\sqcup \mathbb{B}\) 
2. пересечение множеств A и B:
    \(A\cap B :=\{x|(x\in A)\land (x\in B)\}\)
3. разность множества
    \(A\setminus B:=\{x|(x\in A), \land (x\notin B)\}\)

   Разность между множеством М и содержащимся в нём подмножеством А обычно называют А в М и обозначают через \[C_M A\] или \[CA\] если понятно к какому множеству дополнение.

   - Пример. Плавила де Моргана:
      \[C_M(A\cup B)=C_MA\cap C_MB\]
      
      \[C_M(A\cap B)=C_MA\cup C_MB\]
      докажем первое из равенств
   #+begin_proof 
      \((x\in C_M(A\cup B))\implies 
      (x\notin (A\cup B)) \implies
      ((x\notin A)\land (x\notin B)) \implies (x\in C_MA)\land (x\in C_M B)\implies (x\in(C_MA\cap C_MB)) \)

      \[C_M(A\cup B)\subset C_MA\cap C_MB\]
      
      \((x\in (C_MA\cap C_M B)) \implies ((x\in C_MA)\land (x\in C_MB))\implies ((x\notin A)\land (x\notin B)) \implies (x\notin (A\cup B)) \implies (x\in C_M(A\cup B)) \)
      
      \[(C_MA\cap C_M B)\subset C_M(A\cup B)\]
   #+end_proof
4. Прямое (декартово) произведение множеств.

   Для любой пары двух множеств можно образовать новое множество \[\{A, B\}=\{B, A\}\]  элементами которого являются только они. Множество состоит из двух эл-тов если множ-ва не равны и одного в обратном случае.

   Существует так же упорядоченная пара
   \[(A, B)=(C, D) \]  где \[A=C\] \[ B=D\]

   \[A\neq B \implies (A, B)\neq (B, A)\]

   Пусть, X и Y — произвольные множества.
   
   \[\mathbb{X}\times \mathbb{Y} := \{(x, y) |(x \in \mathbb{X}) \land (y\in \mathbb{Y})\}\]

   для \(\mathbb{A}_n\) множеств.
   \(A_1 \times A_2 \times ... \times A_n = \{ (a_1, a_2, ..., a_n) | a_i \in A_i \}\)
   декартово произведение:
   \( \mathbb{A}\times \mathbb{A}=\mathbb{A}^2\)
   
   Образованное всеми упорядоченными парами (x, y) первый член которых есть элемент из Х, а второй член — элемент из Y, называется прямым или декартовым произведением множеств X и Y.
   
   \[X\neq Y \implies X\times Y\neq Y\times X\]
   зам. известная всем система декартовых координат превращает эту плоскость в произведения числовых осей.
** свойство операций  над множествами
| Свойство         | Символьно                                         |
|------------------+---------------------------------------------------|
| Коммутативность  | $\mathbb{A}\cup \mathbb{B}=\mathbb{B}\cup \mathbb{A}$ |
|                  | $\mathbb{A}\cap \mathbb{B}=\mathbb{B}\cap \mathbb{A}$ |
| Ассоциативность  | $A\cup (B\cup C)=(A\cup B)\cup C$                           |
| Дистрибутивность | $A\cup(B\cap C)=(A\cup B)\cap(A\cup C)$                        |
|                  | $A\cap(B\cup C)=(A\cap B)\cup(A\cap C)$                        |
| Идемпонтность    | $A\cup A=A$                                        |
|                  | $A\cap A=A$                                        |
|                  |                                                   |
|                  | $A\cup \varnothing = A$                            |
|                  | $A\cap \varnothing = A$                            |
* Парадокс Рассела (1872-1970)
К множество всех множеств
\(p(K)\) - множество не содержит себя в качестве своего элемента

\(K={M|P(M)}\)

\(K\in K\implies \neg P(k)\implies K\notin K\)

\(K\notin K \implies P(k)\implies K\in K\)

В современной математике понятие множества вносится аксиоматически.

Множество обладает определённым набором свойств, описание этих свойств составляет всю аксиоматику.

В рамках этих аксиом множество всех множеств не является множеством.

* Аксиоматика теории множеств
1. Аксиома объёмности. / The axiom of extension
   
   Множества равны тогда и только когда имеют одни и те же элементы.
   \(A=B => \forall x((x\in  \mathbb{A} )\iff (x\in \mathbb{B}))\)
2. Аксиома выделения. / Comprehension scheme
   
    Любому множеству А и свойству Р отвечает множество В, элементы которого суть те же элементы множества А, которые обладают свойством Р.
    \(B=\{x\in \mathbb{A}|P(x)\}\)
   
    Из этой аксиомы следует, что разность множеств, в том числе дополнение — множества.
3. Аксиома пустого множества / Empty set axiom
   
   Существует пустое множество
       \(\varnothing =\{x\in X| x\neq x\}\)
    учитывая 1 аксиому пустое множество единственно.
4. Аксиома объединения.  / Axiom of Union
   
   Для каждого семейства \(\mathbb{M}\) существует множество, которое является объединением \(\bigcup \mathbb{M}\), содержащим все элементы из \(\mathbb{M}\)

   причём(где X это элемент семейства):

   \(x \in \bigcup \mathbb{M}\iff \exists \mathbb{X} (( \mathbb{X}\in \mathbb{M}))\)

   эта аксиома позволяет определить пересечение семейства множеств как множество:.

   \(\bigcap \mathbb{M} := \{x\in \bigcup \mathbb{M} | \forall \mathbb{X}((\mathbb{X}\in \mathbb{M})\implies (x\in \mathbb{X}))\}\)
5. Аксиома пары / Pairing axiom
   
    Для любых множеств \(X\) и \(Y\) существует множество \(Z\) такое, что содержит все и исключительно элементы этих множеств.
    
    если множества равны, то Z состоит из одного элемента, обозначается так:
    \(\{\mathbb{X}, \mathbb{Y}\}\)
    
    Эта аксиома помогает ввести упорядоченную пару:
    \((\mathbb{X}, \mathbb{Y}):=\{\mathbb{X}\}, \{\mathbb{X}, \mathbb{Y}\}\) 
6. Аксиома множества подможеств /Power Set Axiom
   
   Для каждого множества существует множество \(\mathcal{P}(\mathbb{X})\) состоящее из элементов всех подмножеств X.

   Так можно ввести прямое произведение множеств.
   \(\mathbb{X}\times \mathbb{Y}:= \{p\in \mathcal{P}(\mathcal{P}(\mathbb{X})\cup \mathcal{P}(\mathbb{Y}))|p=(x,y)\land (x\in \mathbb{X})\land (x\in \mathbb{Y})\}\)
7. Аксиома бесконечности / Infinity axiom
   
   Введём понятие последователя \(\mathbb{X}^+=\mathbb{X}\cup \{\mathbb{X}\}\) (добавляет к множеству одноэлементное множество \(\mathbb{X}\)).
   
   Назовём множество индуктивным, если оно содержит пустое множество и последователь каждого своего элемента.
   
   Аксиома утверждает, что индуктивные множества существуют.

   Аксиома позволяет определить модель множества \(\mathbb{N}_0\) натуральных чисел, как пересечение индуктивных множеств, т. е. наименьшее индуктивное множество. Соответственно его элементами являются:
   \(\varnothing, \varnothing^+=\varnothing\cup \{\varnothing\}=\{ \varnothing \}, \{\varnothing\}^+=\{\varnothing\}\cup \{\{\varnothing\}\}, ...,\)
   Так же являющееся моделью множества натуральных чисел.

   в общем, можно сформулировать эту аксиому так:
   \(\exists x(\varnothing \in \mathbb{X} \land \forall y(y\in \mathbb{X} \to y\cup \{y\}\in \mathbb{X}))\)
8. Аксиома подстановки / Replacement Axiom
   
   Есть множество \(\mathbb{X}\), множества \((\mathbb{N}_i)^n_{i=1}\), существует закон, который ассоциирует для \(\forall x\in X\) и для каждой последовательности множеств \((\mathbb{N}_i)^n_{i=1}\)  уникальное множество \(\Phi(x, \mathbb{N},... \mathbb{N}_n)\):
   
   \(\{y|\forall x\in \mathbb{X} y=\Phi(x, \mathbb{N}_1,..., \mathbb{N}_n)\}\)
   [[https://people.maths.ox.ac.uk/~knight/lectures/formalaxioms.pdf][взято отсюда]]
9. Аксиома выбора / Axiom of Choice
   
   Для каждого семейства непустых попарно непересекающихся множеств существует множество \(\mathbb{C}\) такое, что какого бы не было множество \(\mathbb{X}\) данного семейства, множество \(\mathbb{X}\cap \mathbb{C}\) состоит из одного элемента.

* вкратце о числах 
<2025-09-03 Wed>
\(x\in \mathbb{X}\)
\(\mathbb{A}\subset \mathbb{X}\)

\(C_m A=\{x\in M| x\notin M\}\)
\(A=B\iff A\subset B \land B\subset A\)

\(\mathbb{N}=\{1, 2, 3, ...\}\) 
\(\mathbb{Z}=\{0, \pm 1, \pm 2, ...\}\)
\(\mathbb{Q}=\{\frac{p}{q}|p\in \mathbb{Z}\land q\in \mathbb{N}\}\)

Любое рац число может быть записанно в виде конечной дроби, либо периодической дроби.

\(\sqrt{2}\notin \mathbb{Q}\)

геометрическая интерпретация множества действительных чисел.
введение таких точек на прамой L взаимоодназначное соответствие между точками и множеством R. Направление задаваемое лучом с вершиной в точке ноль и содержащим 1 является положительным.

\(\forall x\in \phi \exists ! x\in \mathbb{R}\)
x  длина отрезка икс
x - Длина положительная ОХ, если икс лежит правее 0.
х - длина отрезка ОХ отрицательная, если Х правее.

Такую прямую для которой установлено взаимооднозначное соответствие с R, называют числовой(координатной осью)
При рассмотрении числовых множеств(подможеств R действительных) принято использовать геом-кий язык.

* Обозначение некоторых числовых множеств
\(a\in \mathbb{R}, b\in \mathbb{R}, a<b\)

ограниченные числовые промежутки.:
    \([a,b]=\{x\in \mathbb{R}|a\leq x\leq b\}\) отрезок
    \((a, b)=\{x\in \mathbb{R}|a<x<b\}\)  интервал
    \((a, b]=\{x\in \mathbb{R}|a<x\leq b\}\) полуинтервал
    \([a, b)=\{x\in \mathbb{R}|a\leq x<b\}\) полуинтервал


неограниченные числовые промежутки:

    \((- \infty ,a ) =\{x\in \mathbb{R}|x<a\}\)
    \((- \infty ;a ] =\{x\in \mathbb{R}|x\leq a\}\)
    \((a,+ \infty  ) =\{x\in \mathbb{R}|x> a\}\)
    \([a,+ \infty  ) =\{x\in \mathbb{R}|x\geq a\}\)

\((-\infty, + \infty)= \mathbb{R}\)

зам. \((a,b)=\{x\in \mathbb{R}|a<x<b|\}\)
\(\{a, b\}\) - множество из a, bи

Расширенная числовая прямая, или проективно рассширенная:
\(\widehat{\mathbb{R}}=\mathbb{R} \cup \{\infty\}\)

Аффинно расширенная бесконечность:
\(\overline{\mathbb{R}} = \mathbb{R} \cup \{-\infty, +\infty\} = [-\infty, +\infty]\)

* мощность множества
Пусть А и В - два конечных множества.
\(A=\{a, b, c, d, ...\}\)
\(A=\{\alpha, \beta, \gamma, \delta, ...\}\)
Одинаково или нет количество элементов в этих множествах можно решить не считая их элементы, а устанавливая соответствия. Для этого способа сравнения хар-но то, что для каждого эле-та одного множества указывается один и только один эл-т другого мн-ва. 

Определение:
    Пусть Х и У - два множества.
    Правило \(\phi\) которое каждому эл-ту х из множества Х ставит в соответствие один и только один эл-т у из множества У причём, каждый эл-т у из У оказывается соотнесённый только одному х из множества Х, называется взаимно однозначным соответствием между множествами Х и У.

Замечание, взаимно однозначное соответствие носит название биективное отображение. Биекция.

Если между множествами \(\mathbb{A}\) и \(\mathbb{B}\)(не обязательно конечными) можно установить взаимно однозначное соответствия, то такие мно-ва называются экви-ми или равно мощными.
\(A\sim B\)
отношение равномощности разбивает соотножение на классы эквивалентных множ-в
Множества одного класса эквивалентности имеют одинаковое количество элементов(равномощных)

Опред. Класс которому принадлежит мно-во Х, называется мощностью множества Х или кардинальным числом(кардиналом) множества Х и обозначается \(\text{Card }\mathbb{X}\).
если \(\mathbb{X}\sim \mathbb{Y}\) то пишут \(\text{Card} \mathbb{X}=\text{Card}\mathbb{Y}\)

Зам. Если берём \(\mathbb{X}\in \mathbb{Y}\) то \(\text{Card} \mathbb{X}<\text{Card} \mathbb{Y}\)

такой способ определения мощности можно использовать и для ин-ти множеств

пр-р
 \(\mathbb{N}=\{1, 2,..\}\)
   \(M=\{2n|n\in \mathbb{N}\}\)
   \(M\in N\)
   \(\text{Card} \mathbb{M}=\text{Card} \mathbb{N}\)

   Опред. Все ин-ти мно-ва для которых может быть установлено взаим-одн соответвие с множеством натуральных чисел называются счётными.

   Зам. Все эл-ты счётных множеств могут быть занумерованы в ин-ти последовательность

   Для ин-ти мно-в возможна ситуация когда одно является подмно-вом другого, при этом оба равно мощные. 

   \( \mathbb{N}=\alpha\)
   
   \((0,1)\) - не счётное
   > допустим оно счётное, если это так, то мы можем их занумеровать
   но так не получится, потому что можно сделать наискосок новые индексы. <

   \(\text{Card}(a, b)=c = \text{Card}\ \mathbb{R}=c\)
   \(x\to \frac{x}{1-|x|}\)  f устанавливае взаи-одн соответствие между (0, 1) и R  
   
* функция
  Пусть \(\mathbb{X},\ \mathbb{Y}\) - два числовых множеств.
\(\mathbb{X}\in\mathbb{R}, \mathbb{Y}\in\mathbb{R}\)

Опр. Говорят, что есть функция f, определённая на множестве X со значениями в множестве Y, если определён закон(правило, зависимость), по которому каждому элементу из множества X ставится единственный элемент из Y.

\(f:\mathbb{X}\to\mathbb{Y}, \mathbb{X}\to^f\mathbb{Y}^{}^{}\)
\(\mathbb{X}\) - область определения функции f
\(x\in\mathbb{X}\) x - независимая переменная, аргумент функции.


множество всех значений, будем называть множеством значений или областью значений функции.

\(f(a)=\{y\in \mathbb{Y}| \exists x((x\in A)\land y=f(x))\}\)
y - зависимая переменная \(y=f(x)\)


если \(B\subset E(f)\) и \(f(A)=B\) то \(f^{-1}(B)=A\) - прообраз множества \(B\)


Допустим, есть отображение  $f: \mathbb{A} \to \mathbb{B}$ оно

1. сюръективно, или сюръектиция, если \(f(\mathbb{X})=\mathbb{Y}\) т.е. у каждого элемента \(y\) есть прообраз в множестве \(\mathbb{X}\).
2.  инъективно, или инъекция, если $x_1\neq x_2\ x_1, x_2\in \mathbb{Y}$ тогда $f(x_1)\neq f(x_2)$
3.  и биективна, если соблюдается 1 и 2.

Замечание. Для того, чтобы аналитическое выражение \(f(x)=x^2\)  являлось биективным, надо его ограничить.

Замечание. Если отображение \(f:\mathbb{X}\to \mathbb{Y}\) биективно, то возникает отображение \(f^{-1}:\mathbb{Y}\to \mathbb{X}\) каждому элементу \(y\) из множества \(\mathbb{Y}\) ставится в соответствие элемент \(x\) из множества \(\mathbb{X}\) для которого выполняется \(f(x)=y\). Называют обратным отображением для \(f\).

Замечание. Свойство двух отображений быть обратными является взаимным.
