=Если обозначение удобны для открытий..., то поразительным образом сокращается работа мысли.=
Г. Лейбниц(1646-1716) 

<2025-09-02 Tue>

* в основном про логические обозначения
Логическая символика
| знак              | значение                                                         |
|-------------------+------------------------------------------------------------------|
| \(\neg\)             | отрицание                                                        |
| \(\land\)             | конъюкция, союз и                                                |
| \(\lor\)             | дизъюнкция                                                       |
| \(\implies \)     | влечёт                                                           |
| $A \implies B$    | B следует из A, B необходимый признак для A, A достаточный для B |
| \(\iff \) / \(\equiv\) | тождественно равно                                               |
| \(\exists\)             | квантор существования                                            |
| \(\forall\)             | квантор общности                                                 |
| \(:=\)            | со стороны определяемого понятия                                 |
| \(\exists !\)           | единственное существующее                                        |

> начало и конец докозательства < 

| Приоритет символов: |
|---------------------|
| \(\neg\)               |
| \(\cap\)               |
| \(\cup\)               |
| \(\implies\)        |
| \(\iff\)            |

** $$A\iff B$$

\((A\implies B)\cap (B\implies A)\)
при док-ве равносильности:
1) \(A\implies B\) необходимость В при необходимости А
2) \(B\implies A\) достаточность В для А

* Насчёт  множеств
С конца XIX — начала XX столетия наиболее универсальным языком математики стал язык теории множеств.

создатель теоретико-множественного языка математики и теории бесконечных множеств Георг Картер (1845-1918)

=Под множеством мы понимаем объединение в одно целое определенных, вполне различимых объектов нашей интуиции или нашей мысли.=

В Картеровской "наивной" теории множеств:
1. множество может состоять из любых различимых объектов.
2. множество однозначно определяется набором составляющих объектов.
3. любое свойство может определять множество объектов.
   
** обозначения 
Способы задания множеств:
1. Словесный
2. Перечисление эл-тов \(\mathbb{A}=\{1, 2, 3\}\)
3. Через указание характеристического свойства  \(P(x)\) \(\mathbb{A}=\{x|P(x)\}\)
4. Специальный, он используется для обозначения числовых промежутков и числовых множеств.

Если x — объект, P — свойство, \(P(x)\)  — x обладает свойством P.
\(\{x|P(x)\}\) множество обладающих свойством x.

Элемент множества — это объект, который принадлежит множество. \(a\in \mathbb{A}\)
\(x\in \mathbb{X}\) - элемент множества

\(x\neg \in \mathbb{X}\)  или \(x\notin \mathbb{X}\) - не элемент множества

\(\forall x((x\in A)\iff(x\in B))\) означает \(A=B\)

Если любой элемент А является элементом множества В, то пишут \(A\subset B\) и говорят что А является подмножеством В.

Отношение включения:
\((A\subset B):=\forall x((x\in A)\implies (x\in B))\)

Если \(A\subset B\) и \(A\neq B\) то включение строгое и А собственное множество В.

Если М — множество, то любое свойство Р выделяет в подмножество М те элементы которые обладают этим свойством:
\[\{x\in M|P(x)\}\]

=>

\[M=\{x\in M|x\in M\}\]

если же взять свойство, которому не соответствует ни один элемент из множества

\[\varnothing =\{x\in M|x\neq x\}\]

\(A=B \iff\{x\in A | (x\in A)\iff (x\in B)\}\)

получится пустое множество
** операции над множествами
1. объединение множеств A и B:
    \(A\cup B:=\{x|(x\in A)\lor (x \in B)\}\)
    
2. пересечение множеств A и B:
    \(A\cap B :=\{x|(x\in A)\land (x\in B)\}\)
    
3. разность множества
    \(A\setminus B:=\{x|(x\in A), \land (x\notin B)\}\)

   Разность между множеством М и содержащимся в нём подмножеством А обычно называют А в М и обозначают через \[C_M A\] или \[CA\] если понятно к какому множеству дополнение.
   - Пример. Плавила де Моргана:
      \[C_M(A\cup B)=C_MA\cap C_MB\]
      
      \[C_M(A\cap B)=C_MA\cup C_MB\]
      докажем первое из равенств
      <
      
      \((x\in C_M(A\cup B))\implies 
      (x\notin (A\cup B)) \implies
      ((x\notin A)\land (x\notin B)) \implies (x\in C_MA)\land (x\in C_M B)\implies (x\in(C_MA\cap C_MB)) \)

      \[C_M(A\cup B)\subset C_MA\cap C_MB\]
      
      \((x\in (C_MA\cap C_M B)) \implies ((x\in C_MA)\land (x\in C_MB))\implies ((x\notin A)\land (x\notin B)) \implies (x\notin (A\cup B)) \implies (x\in C_M(A\cup B)) \)
      
      \[(C_MA\cap C_M B)\subset C_M(A\cup B)\]
      >

4. Прямое (декартово) произведение множеств.
   Для любой пары двух множеств можно образовать новое множество \[\{A, B\}=\{B, A\}\]  элементами которого являются только они. Множество состоит из двух эл-тов если множ-ва не равны и одного в обратном случае.

   Существует так же упорядоченная пара
   \[(A, B)=(C, D) \]  где \[A=C\] \[ B=D\]

   \[A\neq B \implies (A, B)\neq (B, A)\]

   Пусть, X и Y — произвольные множества.
   
   \[\mathbb{X}\times \mathbb{Y} := \{(x, y) |(x \in \mathbb{X}) \land (y\in \mathbb{Y})\}\]
   
   декартово произведение:
   \( \mathbb{A}\times \mathbb{A}=\mathbb{A}^2\)
   
   Образованное всеми упорядоченными парами (x, y) первый член которых есть элемент из Х, а второй член — элемент из Y, называется прямым или декартовым произведением множеств X и Y.
   
   \[X\neq Y \implies X\times Y\neq Y\times X\]
   
** свойство операций  над множествами
Коммутативность
\(\mathbb{A}\cup \mathbb{B}=\mathbb{B}\cup \mathbb{A}\) 
\(\mathbb{A}\cap \mathbb{B}=\mathbb{B}\cap \mathbb{A}\) 
Ассоциативность
\(A\cup (B\cup C)=(A\cup B)\cup C\)
Дистрибутивность
\(A\cup(B\cap C)=(A\cup B)\cap(A\cup C)\)
\(A\cap(B\cup C)=(A\cap B)\cup(A\cap C)\)
Идемпонтность
\(A\cup A=A\)
\(A\cap A=A\)

\(A\cup \varnothing = A\)
\(A\cap \varnothing = A\)

* Парадокс Рассела (1872-1970)
К множество всех множеств
\(p(K)\) - множество не содержит себя в качестве своего элемента

\(K={M|P(M)}\)

\(K\in K\implies \neg P(k)\implies K\notin K\)

\(K\notin K \implies P(k)\implies K\in K\)

В современной математике понятие множества вносится аксиоматически.

Множество обладает определённым набором свойств, описание этих свойств составляет всю аксиоматику.

В рамках этих аксиом множество всех множеств не является множеством.

* Аксиоматика теории множеств
1. Аксиома объёмности. / The axiom of extension
   Множества равны тогда и только когда имеют одни и те же элементы.
   \(A=B => \forall x((x\in  \mathbb{A} )\iff (x\in \mathbb{B}))\)
   
2. Аксиома выделения. / The axiom of specification
   Любому множеству А и свойству Р отвечает множество В, элементы которого суть те же элементы множества А, которые обладают свойством Р.
   \(B=\{x\in \mathbb{A}|P(x)\}\)
   
   \(\varnothing =\{x\in X| x\neq x\}\)
   учитывая 1 аксиому пустое множество единственно.
   
   Из этой аксиомы следует, что разность множеств, в том числе дополнение — множества.
3. Аксиома объединения.  
   Для любого множества М существует множество \(\bigcup M\) называемое объединением множества M, состоящее только из тех элементов которые содержатся в множестве М.

   \(x \in \bigcup M\iff \exists X ((X\in M))\)

   \(\bigcap M := \{x\in \bigcup M | \forall X((X\in M)\implies (x\in X))\}\)
   
4. Аксиома пары
   
