* вкратце о числах 
<2025-09-03 Wed>
\(x\in \mathbb{X}\)
\(\mathbb{A}\subset \mathbb{X}\)

\(C_m A=\{x\in M| x\notin M\}\)
\(A=B\iff A\subset B \land B\subset A\)

\(\mathbb{N}=\{1, 2, 3, ...\}\) 
\(\mathbb{Z}=\{0, \pm 1, \pm 2, ...\}\)
\(\mathbb{Q}=\{\frac{p}{q}|p\in \mathbb{Z}\land q\in \mathbb{N}\}\)

Любое рац число может быть записанно в виде конечной дроби, либо периодической дроби.

\(\sqrt{2}\notin \mathbb{Q}\)

геометрическая интерпретация множества действительных чисел.
введение таких точек на прамой L взаимоодназначное соответствие между точками и множеством R. Направление задаваемое лучом с вершиной в точке ноль и содержащим 1 является положительным.

\(\forall x\in \phi \exists ! x\in \mathbb{R}\)
x  длина отрезка икс
x - Длина положительная ОХ, если икс лежит правее 0.
х - длина отрезка ОХ отрицательная, если Х правее.

Такую прямую для которой установлено взаимооднозначное соответствие с R, называют числовой(координатной осью)
При рассмотрении числовых множеств(подможеств R действительных) принято использовать геом-кий язык.

* Обозначение некоторых числовых множеств
\(a\in \mathbb{R}, b\in \mathbb{R}, a<b\)

ограниченные числовые промежутки.:
    \([a,b]=\{x\in \mathbb{R}|a\leq x\leq b\}\) отрезок
    \((a, b)=\{x\in \mathbb{R}|a<x<b\}\)  интервал
    \((a, b]=\{x\in \mathbb{R}|a<x\leq b\}\) полуинтервал
    \([a, b)=\{x\in \mathbb{R}|a\leq x<b\}\) полуинтервал


неограниченные числовые промежутки:

    \((- \infty ,a ) =\{x\in \mathbb{R}|x<a\}\)
    \((- \infty ;a ] =\{x\in \mathbb{R}|x\leq a\}\)
    \((a,+ \infty  ) =\{x\in \mathbb{R}|x> a\}\)
    \([a,+ \infty  ) =\{x\in \mathbb{R}|x\geq a\}\)

\((-\infty, + \infty)= \mathbb{R}\)

зам. \((a,b)=\{x\in \mathbb{R}|a<x<b|\}\)
\(\{a, b\}\) - множество из a, bи

Расширенная числовая прямая, или проективно рассширенная:
\(\widehat{\mathbb{R}}=\mathbb{R} \cup \{\infty\}\)

Аффинно расширенная бесконечность:
\(\overline{\mathbb{R}} = \mathbb{R} \cup \{-\infty, +\infty\} = [-\infty, +\infty]\)

* мощность множества
Пусть А и В - два конечных множества.
\(A=\{a, b, c, d, ...\}\)
\(A=\{\alpha, \beta, \gamma, \delta, ...\}\)
Одинаково или нет количество элементов в этих множествах можно решить не считая их элементы, а устанавливая соответствия. Для этого способа сравнения хар-но то, что для каждого эле-та одного множества указывается один и только один эл-т другого мн-ва. 

Определение:
    Пусть Х и У - два множества.
    Правило \(\phi\) которое каждому эл-ту х из множества Х ставит в соответствие один и только один эл-т у из множества У причём, каждый эл-т у из У оказывается соотнесённый только одному х из множества Х, называется взаимно однозначным соответствием между множествами Х и У.

Замечание, взаимно однозначное соответствие носит название биективное отображение. Биекция.

Если между множествами \(\mathbb{A}\) и \(\mathbb{B}\)(не обязательно конечными) можно установить взаимно однозначное соответствия, то такие мно-ва называются экви-ми или равно мощными.
\(A\sim B\)
отношение равномощности разбивает соотножение на классы эквивалентных множ-в
Множества одного класса эквивалентности имеют одинаковое количество элементов(равномощных)

Опред. Класс которому принадлежит мно-во Х, называется мощностью множества Х или кардинальным числом(кардиналом) множества Х и обозначается \(\text{Card }\mathbb{X}\).
если \(\mathbb{X}\sim \mathbb{Y}\) то пишут \(\text{Card} \mathbb{X}=\text{Card}\mathbb{Y}\)

Зам. Если берём \(\mathbb{X}\in \mathbb{Y}\) то \(\text{Card} \mathbb{X}<\text{Card} \mathbb{Y}\)

такой способ определения мощности можно использовать и для ин-ти множеств

пр-р
 \(\mathbb{N}=\{1, 2,..\}\)
   \(M=\{2n|n\in \mathbb{N}\}\)
   \(M\in N\)
   \(\text{Card} \mathbb{M}=\text{Card} \mathbb{N}\)

   Опред. Все ин-ти мно-ва для которых может быть установлено взаим-одн соответвие с множеством натуральных чисел называются счётными.

   Зам. Все эл-ты счётных множеств могут быть занумерованы в ин-ти последовательность

   Для ин-ти мно-в возможна ситуация когда одно является подмно-вом другого, при этом оба равно мощные. 

   \( \mathbb{N}=\alpha\)
   
   \((0,1)\) - не счётное
   > допустим оно счётное, если это так, то мы можем их занумеровать
   но так не получится, потому что можно сделать наискосок новые индексы. <

   \(\text{Card}(a, b)=c = \text{Card}\ \mathbb{R}=c\)
   \(x\to \frac{x}{1-|x|}\)  f устанавливае взаи-одн соответствие между (0, 1) и R  
   
* функция
  Пусть \(\mathbb{X},\ \mathbb{Y}\) - два числовых множеств.
\(\mathbb{X}\in\mathbb{R}, \mathbb{Y}\in\mathbb{R}\)

Опр. Говорят, что есть функция f, определённая на множестве X со значениями в множестве Y, если определён закон(правило, зависимость), по которому каждому элементу из множества X ставится единственный элемент из Y.

\(f:\mathbb{X}\to\mathbb{Y}, \mathbb{X}\to^f\mathbb{Y}^{}^{}\)
\(\mathbb{X}\) - область определения функции f
\(x\in\mathbb{X}\) x - независимая переменная, аргумент функции.


множество всех значений, будем называть множеством значений или областью значений функции.

\(f(a)=\{y\in \mathbb{Y}| \exists x((x\in A)\land y=f(x))\}\)
y - зависимая переменная \(y=f(x)\)


если \(B\subset E(f)\) и \(f(A)=B\) то \(f^{-1}(B)=A\) - прообраз множества \(B\)


Допустим, есть отображение  $f: \mathbb{A} \to \mathbb{B}$ оно

1. сюръективно, или сюръектиция, если \(f(\mathbb{X})=\mathbb{Y}\) т.е. у каждого элемента \(y\) есть прообраз в множестве \(\mathbb{X}\).
2.  инъективно, или инъекция, если $x_1\neq x_2\ x_1, x_2\in \mathbb{Y}$ тогда $f(x_1)\neq f(x_2)$
3.  и биективна, если соблюдается 1 и 2.

Замечание. Для того, чтобы аналитическое выражение \(f(x)=x^2\)  являлось биективным, надо его ограничить.

Замечание. Если отображение \(f:\mathbb{X}\to \mathbb{Y}\) биективно, то возникает отображение \(f^{-1}:\mathbb{Y}\to \mathbb{X}\) каждому элементу \(y\) из множества \(\mathbb{Y}\) ставится в соответствие элемент \(x\) из множества \(\mathbb{X}\) для которого выполняется \(f(x)=y\). Называют обратным отображением для \(f\).

Замечание. Свойство двух отображений быть обратными является взаимным.

