* Алгебра изучает алгебраические структуры. * 
Определение. Алгебраической структурой мы будем называть множество \(\mathbb{M}\) вместе с набором операций.

\(\mathbb{M}\) - множество, \(\mathbb{M}\times \mathbb{M}=\{(a,b)|a,b\in \mathbb{M}\}\)

** Функция 
Функция — это вид бинарного отношения, при котором каждому элементу множества А, соответствует не более одного элемента из В.

Бинарное отношение — между элементами множеств А и В это подмножество декартова произведения. 

\((\mathbb{X}, \mathbb{Y}, f), f\subset (\mathbb{X}\times \mathbb{Y})\)
множество первых элементов пар, называется областью определения отношения f(D(f)), а множество вторых элементов пар областью значений(E(f)).

Если бинарное отношение — функция из множества Х в множество У и \(\mathbb{X}=D(f)\) то F называют отображением X в У.

Допустим, есть \(f: \mathbb{A} \to \mathbb{B}\)
1) \(f\) — инъективная, или инъекция, если \(a_1\neq a_2\) тогда \(f(a_1)\neq f(a_2)\)
2) \(f\) — сюръективная, или сюръектиция, если \(\forall b\in \mathbb{B} \implies a\in \mathbb{A} \{f(a)=b\}\) 
3) и биективна, если соблюдается 1 и 2.

** Бинарная операция 

Берётся пара каких-то элементов и по какому-то правилу получаете один элемент(существуют операции с использованием большего количества элементов)
$*: M \times M(a,b) \rightarrow M(a * b)$

   \(\forall x, y\in \mathbb{S}\ \exists !\ z\in \mathbb{S}(z=x*y)\)

Будем называть \((\mathbb{N}, +)\) - алгеброй(+ - любой знак)
если операция записана с помощью знака +, то такая форма записи называется аддитивной.

с помощью знака умножения мультипликативной.

Примеры бинарной операции:

    \(\mathbb{N}=\{1, 2, 3, ...\} \) 
    
    \(\mathbb{Z}=\{0, \pm 1, \pm 2, ...\} \)
    
    \(\mathbb{Q}=\{\frac{p}{q}|p, q\in \mathbb{Z}\land q\ne 0\}\)

    1) \((\mathbb{N}, +)\)

        \((\mathbb{Z}, +)\)
    3) \(\mathbb{V}\) = { Вектора на плоскости }
    4) множество, \((\text{Map}(m,m), \circ)\) (Map - множество отображений)
    \(\{\mathbb{M} \xrightarrow{f} \mathbb{Y}\}\)
    
    \(\mathbb{M}\xrightarrow{g} \mathbb{M}\xrightarrow{f} M\) или \(f(g(x))\)

Опр. множество на котором задана бинарная операция называется группоидом(результат должен принадлежать тому же множеству).

\((\mathbb{N}, +)\) - группоид

\((\mathbb{Z}, +)\) - группоид

\((\mathbb{S}, *)\) будем называть алгеброй.

** Гомоморфность  / homomorphism
Определение. есть \((\mathbb{M}, \circ)\)  и \((\mathbb{N}, *)\) они гомоморфны если есть  \(f: \mathbb{M}\to \mathbb{N}\)

\(\forall a, b \in \mathbb{M}(f(a \circ b) =f(a)*f(b))\)

И изоморфны, если гомоморфны и биективны обозначается:

\( (\mathbb{M}, \circ)\simeq (\mathbb{N}, *)\)

Само отображение f называется изоморфизмом этих структур.

Пример: \(a\to 2^a\)  \((\mathbb{Q}, +)\simeq (\mathbb{R}^+, *)\)

* Простейшие свойства 
1) $\forall a, b, c \in \mathbb{R}(a + (b + c) = (a + b) + c)$ (ассоциативность)
2) $\forall a \in \mathbb{R} \implies a + 0 = 0 + a = a$ 
3) $\forall a \in \mathbb{R}, \exists! (-a) \in \mathbb{R}\  (a + (-a) = 0) \land ((-a) + a = 0)$
4) $\forall a, b \in \mathbb{R}, \, (a + b = b + a)$ (коммутативность)
5) $\forall a, b, c \in R, \, a(bc) = (ab)c$ (ассоциативность)
6) $\forall a \in R, \, a \cdot 1 = 1 \cdot a = a$
7) $\forall a \in R, \, a \neq 0 \implies \exists! a^{-1} \in R \text{ such that } aa^{-1} = 1$
8) $\forall a, b \in R, \, ab = ba$
9) $\forall a, b\in \mathbb{R}(a(b+c)=ab+ac)$
10) \(\forall a,b \in \mathbb{G}\exists ! c\in G(c=a*b)\)
при условии соблюдении 10 аксиомы:

    Аддитивная полугруппа это множество \(\mathbb{G}\) с бинарными операциями удволетворяющими аксиоме 1).
    
    Аддитивная группа это множество \(\mathbb{G}\) с бинарными операциями удволетворяющими аксиомам с 1) по 3).
    
    Абелева группа — группа + 4)
    
    Это множество \(\mathbb{R}\) с двумя бинарными операциями 1), 4), 9)
    
    Ассоциативное кольцо + 5).
    
    Поле — 1)- 9)
    
\(\theta \subset \mathbb{S}\)  называется нейтральным если \(\forall x\in \mathbb{S}(x*\theta=\theta*x=x)\)

в аддитивной записи, нейтральный элемент — нулевой. в мультипликотивной — единичный(E).

Пусть \(\mathbb{S}\) группоид содержащий нейтральный элемент тогда элемент \(a'\) называется симметричным элементу а, если \(a*a'=a'*a=\theta\)

при аддитивной форме записи симмитричный элемент называется противоположным, при мультипликативной — обратной.
* Основная теорема арифметики [пример, не закончено, не обязательно читать] 
// будет дополнятся [[https://www.youtube.com/watch?v=T45ZtSk3d38][взято отсюда]]

Примеры:

1) \(\mathbb{Z}\) — коммутативное, ассоциативное кольцо с единицей. 

\(\mathbb{Z}^\times =\{a\in \mathbb{Z}| \exists a^{-1}^{}: aa^{-1}=1\}=\{\pm 1\} \)

\((\mathbb{Z}^\times, \cdot)\) — Аббелева группа.

Опр. \(p\in \mathbb{Z}\)    — простое, если необратимо \(p=m*n\), то \(m\in \mathbb{Z}^\times\) или \(n\in \mathbb{Z}^\times\)

** Основная теорема арифметики
    Любое ненулевое целое не равное \(\pm1\) число единственным образом представляется в виде произведения простых чисел( с точностью до перестановки и умножения на обратимые).

    \(m=p_1...p_k=q_1...q_s\)
    \(p_i, q_i\) — простые
    то \(k=s\) с точностью до перестановки \(p_i=r_iq_i; r=\pm 1\)

    Док. существования. Если число простое, то оно уже разложено, если непростые  числа надо разложить, так как числа уменьшаются, то рано или поздно мы придём к простым числам. \(n=n_1*n_2\) 
    Определение делисмости. \(a, b\in \mathbb{N}, b \mid a \iff \exists q \in \mathbb{Z} | a = b \cdot q
\)
    Док. единственности:
    Лемма Евклида:
        p - простое, \(p|ab \implies {a}|{p} \text{ or } {b}|{p}\) 
        
        Лемма эквивалентна основной теореме арифметике
        
        допустим, число имеет два разных разложения
        \(m=p_1...p_k=q_1...q_s\)
        \(p_1\) — простое
        \({p_1}|{q_1...q_s}\), \({p_1}|{q_1}\) или \({p_1}|{q_1...q_s}\)

        \(\exists i\ {p_i}|{q_i}\)
        \(q_i =\pm p_i\)
        Д-во  леммы Евклида
        на \(\mathbb{Z}\) определеннно деление с остатком:
        утв. \(\forall a, b\in \mathbb{Z}\ \exists ! q, r| a=b*q+r, \ 0\leq r < |b|\)
        
        Наибольший общий делитель:
        1) общий делитель (d|b и d|a)
        2) наибольший с таким свойством.

        Алгоритм евклида:
        НОД(a,b) =НОД(a-b, b)

        \(d|a \implies d|a-b \)

* Свойства бинарных отношений заданных на множестве
Пусть задано бинарное отношение \(\Phi\)  на множестве \(\mathbb{ A }\), оно называется
[[https://www.csd.uwo.ca/~mmorenom/cs2214_moreno/notes/9-handout.pdf][примеры взяты отсюдова]]
Более короткая запись \((x, y)\in \Phi\) === \(x\Phi y\)

1. рефлексивным если для \(\forall x, x\in \mathbb{A} \to (x, x)\in y\)
   
   примеры:
   
   \(\mathbb{A}=\{(x,y)|x\leq y\}\)
   
   \(\mathbb{A}=\{(x,y)|x= y \text{ or } x=-y\}\)
   
   \(\mathbb{A}=\{(x,y)|x= y\}\)
3. симметричным, если \(\forall x, y\in \mathbb{A}((x,y)\in y\implies (y, x)\in \phi)\)
   
    \[\mathbb{A} = \{ (x, y) \mid |x| = |y| \} \]
    
    \[\mathbb{A} = \{ (x, y) \mid x = y \} \]
    
    \[\mathbb{A} = \{ (x, y) \mid x + y \leq 3 \} \]
1. транзитивным, если \(\forall x, y\in \mathbb{A}((x, y)\in \phi\land (y, z)\in \phi\implies (x, z)\in\phi)\)
   
   примеры(\(x, y\in \mathbb{Z}\))
   
    \[\mathbb{A} = \{ (x, y) \mid x \leq y \} \]
    
    \[\mathbb{A} = \{ (x, y) \mid x > y \} \]
    
    \[\mathbb{A} = \{ (x, y) \mid |x| = |y| \} \]
    
    \[\mathbb{A} = \{ (x, y) \mid x = y \} \]
3. отношением эквивалентости если соблюдаются предыдущие три свойства.
    Отношение эквивалентности разбивает множество, на котором оно задано на классы эквивалентности — непустые, попарно непересекающиеся подмножества, объединения которого равны а.
4. иррефлексивным (антирефлексивным), если для \(\forall x\in \mathbb{A} ((x, x)\notin \phi)\)
5. антисимметричным, если для
   \(\forall x, y \in \mathbb{A}((x, y)\in\phi\land (y, x)\in \phi \implies x=y)\)
6. отношением порядка, если выполняются 6 и 3.  Порядок называется строгим, если выполняется 5 и нестрогим — 1. Линейным, если выполняется 8.
7. Связным, если \(\forall (x,y) \in \mathbb{A}, x\neq y ((y, x)\in \phi \lor (x, y)\in \phi)\)

* Простейшие свойства групп
 1) Если в группоиде \(S\) cуществует нейтральный элемент (\(\theta\)) — он единственный.
    допустим, есть два нейтральных элемента \(\theta\) и \(\lambda\):
    \(\theta =\theta * \lambda \land \lambda = \lambda * \theta \implies \lambda = \theta\)
    
 2) Если в полугруппе \(S\) cуществует для элемента а существует симметричный/противоположный — он единственный.
    Допустим, для a есть два противоположных элемента a'_1 и a'_2, в таком случае:
    \(a*a'_1=e \land a*a'_2=e \implies a*a'_1=a*a'_2 \implies a'_1=a'_2\)
 3) Для любых a, b уравнение x * a = b имеет единственное решение, равное b * a'(где a' - обратный элемент a), называющееся в аддитивной группе вычитанием и в мультипликативной делением. 
 4) В мультипликативной форме записи понятие натуральной степени элемента можно вести в полугруппе, понятие целой степени — в группе.
        Для нулевой степени нужен нейтральный элемент, а для отрицательной — обратный, для натуральной степени достаточно ассоциативности.

