 Подгруппа   
\(H\subset G\)   называется подгруппой, если относительно операции определённой в \(G\) оно само образует группу.

*Это самые минимальные требования для подгруппы, взяты из abstract algebra. Могут не подойти для основного курса.*
подмножество \(\mathbb{H}\subset \mathbb{G}\) является подгруппой, если
1. \(H\neq \varnothing\)
2. \(\forall x, y \in \mathbb{H}, xy^{-1}\in \mathbb{H}\)
  Для группы должно выполнится четыре условия:
   1. Ассоциативность обеспечена использованием элементов из \(\mathbb{H}\) .
   2. Наличие нейтрального элемента допустим, что \(y=x\) => \(xx^{-1}\in \mathbb{H}( xx^{-1} =\theta \implies \theta \in \mathbb{H})\).
   3. Наличие противоположного => исходя из условия 2 и равенства \(y=x\).
   4. Замкнутость => допустим, что \(y=y^{-1}\) в таком случае \(x(y^{-1})^{-1}\in \mathbb{H} \implies xy\in \mathbb{H}\).
    
   Всякая группа имеет две тривиальных подгруппы(все подгруппы помимо них называются собственными):
      1) \(\{\theta\}\)
      2) \(\mathbb{G}\)

Пусть \(\mathbb{G}\) — мультипликативная группа, \(a\) – её фиксированный элемент.  Если любой элемент \(g\in \mathbb{G}\) записывается в виде \(g=a^n\) для некоторого \(n\in \mathbb{Z}\), то \(\mathbb{G}=<a>\) — циклическая группа с образующим а(или циклическая группа порождённая а)

аналогично циклическая группа определяется в аддитивном случае:
\(<a>=\{na|n\in \mathbb{Z}\} \)

* кольцо
Элементы кольца, обладающие свойством \(a\neq 0\) \(b\neq 0 \) \(\)\(ab=0\) делить нуля.
Коммутативное кольцо с еденицией без делителей нуля называется областью целостности.


\(\mathbb{K}=\{C_0, C_1, C_2, C_3\}\)
| +   | C_0 | C_1 | C_2 | C_3 |
|-----+-----+-----+-----+-----|
| C_0 | C_0 | C_1 | C_2 | C_3 |
| C_1 | C_1 | C_2 | C_3 | C_0 |
| C_2 | C_2 | C_3 | C_0 | C_1 |
| C_3 | C_3 | C_0 | C_1 |  C_2 |

| *   | C_0 | C_1 | C_2 | C_3 |
|-----+-----+-----+-----+-----|
| C_0 | C_0 | C_0 | C_0 | C_0 |
| C_1 | C_0 | C_1 | C_2 | C_3 |
| C_2 | C_0 | C_2 | C_0 | C_2 |
| C_3 | C_0 | C_3 | C_2 | C_1 |

Разность кольца А и б называют суммой a и b.

Замечание. Кольцо можно определить иначе. Кольцом называется алгебра с двумя операциями: сложение и умножение, если относительно операции сложения оно образует абелеву группу, относительно умножения полугруппу и обе операции связаны свойством дистрибутивности.

1) так как кольцо является абелевой группой по сложению, то для его элементов выполняются все свойства абелевых групп и полугрупп по умножению.
2) \(\forall a\in \mathbb{K}(a*0=0*a=0)\)
3) в произвольном кольце справедливо правило знаков \(\forall a, b\in \mathbb{K}\)  \((-a)(-b)=ab\) \((-a)b=a(-b)=-ab\) \(-(a)=a\)
4) \(\forall a, b, c\in \mathbb{K} a(b-c)=ab-ac (b-c)a=ba-ca\)
5) справедлив бином ньютона \(\forall a, b\in \mathbb{K}\forall n\in \mathbb{N} (a+b)^n=\sum ^n_{i=o}C_na^{n-i}b^i\)
   \(C_n^i=\frac{n !}{i!(n-i)!}\)
   Удобно использовать треугольник Паскаля для нахождения коэффициентов.
   

// возможно будет дополняться
