* Основные свойства функций
1) Четность, нечётность функций
   Ф-ция \(f:\mathbb{X}\to \mathbb{R}\) называется чётной, если множество \(\mathbb{X}\) симметрично относительно нуля и \(\forall x\in \mathbb{X}\) выполняется \(f(-x)=f(x)\) (для нечётной \(f(-x)=-f(x)\) )
  замечание. не все функции  являются чётными или нечётными.
   1) \(f(x)=x^2\) - чётная \(f(-x)=(-x)^2=x^2=f(x)\) \(D(f)=R\)
     
   2) \(f(x)=\frac{1}{x}\)   \(D(f)=(\infty, 0)\cup (0, \infty)\)

   3) \(f(x)=2x+1\) \(D(f)=\mathbb{R}\)

теорема:
всякую функцию определённую на симметричном относительно нуля множестве \(\mathbb{X}\) можно представить как сумму чётной и не чётной функции.
\(\Phi (x)=\frac{f(x) -f(-x)}{2}\)
\(\psi(x)=\frac{f(x)+f(-x)}{2}\)
\(\Phi(-x)=\frac{f(-x)-f(x)}{2}=-\frac{f(x)-f{-x}}{2}\)
\(\phi (-x)=\frac{-f(x)+f(x)}{2}\)
\(\Psi(x) +\Phi(x)=f(x)\)

Примеры:
\(f(x)=|x|\)

1) \(f(x)=x^3\) нечётная
2) \(f(x)=\sin(x)\) нечётная
3) \(f(x)=\cos(x)\) чётная

   переодичность функции
   Ф-ия \(f:\mathbb{X}\to \mathbb{R}\) называется периодической функцией, если \(\exits T\neq 0, T> 0\) такое, что \(\forall x\in \mathbb{X}. x+T\in \mathbb{X}\) \(f(x)=f(x+T)=f(x-T)\) наименьшее значение T при котором выполняется равенство 1, называется основным периодом функции. 
   1) \(f(x)=\sin(x)\) f(x+2\pi)= f(x), f(x+4\pi)

   зам. \(f(x)\)   - переодическая основной период равен \(T\) то функция \(g(x)=f(x)\) где \(a\in \mathbb{R}\) a\neq 0 с периодом \(T_1=\frac{T}{|a|}\) 
По условию \(f(x+t)=f(x)\)
\( \(g(x)=f(ax), g(x+t_1)=f(a(x+t_1))= \)
\(f(a(x+\frac{T}{|a|})) [\frac{a}{|a|}=\begin{cases}1, a> 0, \\ -1, a< 0\end{cases}]=f(ax\pm T)=f(ax)=g(x)\)

1) \(f(x)=\cos3x\) \(T=\frac{2\pi}{3}\)
2) \(f(x)=\tan {\frac{x}{3}}\)

   $f(x)=[x]$
   $g(x)=\{x\}$
