Аспекты культуры речи
<2025-09-03 Wed>

* Язык как знаковая система
Язык представляет собой естественно возникшую знаковую систему, которые имеют определённые закономерности развития и отличается способностью к саморегуляции.

С лингвистической точки зрения язык представляет собой упорядоченную взаимосвязь определённых единиц, её образующих, выделяют следующие языковые единицы: фонемы(реализуются в конкретных звуках и изучаются фонетикой), морфемы(части слова, изучаются морфеникой), лексемы(слова, изучаются лексикологией), словосочетания и предложения(изучаются синтаксисом).

* Ключевые функции языка. Ключевые функции языка. Язык и речь
Основные функции языка:
1) Номинативная (с помощью языка мы называем предметы и явления действительности)
2) Коммуникативная (язык как средство общения)
3) Когнитивная (язык как средство мышления, способ познания мира)
4) Аккумулятивная (язык как способ накопления и передачи знаний другим поколениям)
   
Следует различать два тесно связанных понятия: язык и речь. Язык это орудие средства общения, он является общим для всех членов общества и постоянным.

Речь это появление и функционирование языка, она единична для каждого носителя языка, это явление переменное в зависимости от говорящего лица.

* Аспекты культуры речи:
1) Нормативный аспект
2) Коммуникативный аспект
3) Этический аспект
   
Вод культурой речи понимается владение нормами литературного языка в его устной и письменной форме, при котором осуществляется выбор и организация языковых средств, позволяющих в определённой ситуации общения и при соблюдении этики общения обеспечить необходимый эффект достижения коммуникативных задач. 

Нормативный аспект культуры речи. Нормативный аспект культурной речи предполагает соблюдение норм современного литературного языка. 

Языковые нормы это правила использования языковых средств в определённый период развития языка(сейчас г оглушается в к, во времена Пушкина оглушался в х).

На что мы можем опираться:
На сайте института им. Виноградова РАН опубликованы нормативные словари фиксирующие нормы русского современного лит языка при его использовании в качестве гос-го языка РФ:
Орфографический словарь.
Орфоэпический словарь.
Словарь иностранных слов.
Толковый словарь русского языка.

Выделяют нормы: орфоэпические(произносительные нормы), лексические(нормы словаупотребления), морфологические(нормы употребления отдельных частей речи), синтаксические(нормы связи слов)
